import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ─── Indian Food Database (500+ items) ────────────────────────────────
// Each item: { name, servingSize, servingUnit, calories, protein, carbs, fats, category }
// This flat array can be replaced with a CSV import without changing application logic.

const indianFoods = [
  // ═══════════════════════════════════════════════
  // BREADS & ROTIS
  // ═══════════════════════════════════════════════
  { name: 'Chapati (Wheat)', servingSize: 1, servingUnit: 'piece (40g)', calories: 104, protein: 3.0, carbs: 18.0, fats: 2.5, category: 'Bread' },
  { name: 'Roti (Wheat)', servingSize: 1, servingUnit: 'piece (45g)', calories: 120, protein: 3.0, carbs: 20.0, fats: 3.5, category: 'Bread' },
  { name: 'Plain Paratha', servingSize: 1, servingUnit: 'piece (80g)', calories: 260, protein: 5.0, carbs: 30.0, fats: 13.0, category: 'Bread' },
  { name: 'Aloo Paratha', servingSize: 1, servingUnit: 'piece (120g)', calories: 300, protein: 6.0, carbs: 40.0, fats: 13.0, category: 'Bread' },
  { name: 'Gobi Paratha', servingSize: 1, servingUnit: 'piece (110g)', calories: 270, protein: 5.5, carbs: 35.0, fats: 12.0, category: 'Bread' },
  { name: 'Paneer Paratha', servingSize: 1, servingUnit: 'piece (120g)', calories: 320, protein: 10.0, carbs: 32.0, fats: 16.0, category: 'Bread' },
  { name: 'Methi Paratha', servingSize: 1, servingUnit: 'piece (100g)', calories: 250, protein: 6.0, carbs: 30.0, fats: 12.0, category: 'Bread' },
  { name: 'Mooli Paratha', servingSize: 1, servingUnit: 'piece (110g)', calories: 240, protein: 5.0, carbs: 32.0, fats: 11.0, category: 'Bread' },
  { name: 'Naan (Plain)', servingSize: 1, servingUnit: 'piece (90g)', calories: 260, protein: 8.0, carbs: 45.0, fats: 5.0, category: 'Bread' },
  { name: 'Butter Naan', servingSize: 1, servingUnit: 'piece (100g)', calories: 310, protein: 8.0, carbs: 45.0, fats: 10.0, category: 'Bread' },
  { name: 'Garlic Naan', servingSize: 1, servingUnit: 'piece (100g)', calories: 300, protein: 8.5, carbs: 46.0, fats: 9.0, category: 'Bread' },
  { name: 'Kulcha', servingSize: 1, servingUnit: 'piece (90g)', calories: 270, protein: 7.0, carbs: 42.0, fats: 8.0, category: 'Bread' },
  { name: 'Puri', servingSize: 1, servingUnit: 'piece (30g)', calories: 120, protein: 2.0, carbs: 14.0, fats: 6.0, category: 'Bread' },
  { name: 'Bhatura', servingSize: 1, servingUnit: 'piece (80g)', calories: 300, protein: 5.0, carbs: 40.0, fats: 14.0, category: 'Bread' },
  { name: 'Missi Roti', servingSize: 1, servingUnit: 'piece (60g)', calories: 150, protein: 5.0, carbs: 20.0, fats: 5.0, category: 'Bread' },
  { name: 'Makki Ki Roti', servingSize: 1, servingUnit: 'piece (60g)', calories: 130, protein: 3.0, carbs: 22.0, fats: 3.5, category: 'Bread' },
  { name: 'Tandoori Roti', servingSize: 1, servingUnit: 'piece (50g)', calories: 120, protein: 3.5, carbs: 20.0, fats: 2.5, category: 'Bread' },
  { name: 'Roomali Roti', servingSize: 1, servingUnit: 'piece (40g)', calories: 100, protein: 3.0, carbs: 18.0, fats: 2.0, category: 'Bread' },
  { name: 'Laccha Paratha', servingSize: 1, servingUnit: 'piece (80g)', calories: 280, protein: 5.0, carbs: 32.0, fats: 14.0, category: 'Bread' },
  { name: 'Thepla', servingSize: 1, servingUnit: 'piece (50g)', calories: 140, protein: 4.0, carbs: 18.0, fats: 6.0, category: 'Bread' },
  { name: 'Bajra Roti', servingSize: 1, servingUnit: 'piece (60g)', calories: 130, protein: 3.5, carbs: 22.0, fats: 3.0, category: 'Bread' },
  { name: 'Jowar Roti', servingSize: 1, servingUnit: 'piece (55g)', calories: 115, protein: 3.5, carbs: 21.0, fats: 2.5, category: 'Bread' },
  { name: 'Ragi Roti', servingSize: 1, servingUnit: 'piece (55g)', calories: 110, protein: 3.0, carbs: 22.0, fats: 1.5, category: 'Bread' },
  { name: 'Appam', servingSize: 1, servingUnit: 'piece (80g)', calories: 120, protein: 2.5, carbs: 24.0, fats: 1.5, category: 'Bread' },
  { name: 'Pathiri', servingSize: 1, servingUnit: 'piece (40g)', calories: 95, protein: 2.5, carbs: 18.0, fats: 1.0, category: 'Bread' },
  { name: 'Luchi', servingSize: 1, servingUnit: 'piece (30g)', calories: 110, protein: 2.0, carbs: 14.0, fats: 5.5, category: 'Bread' },
  { name: 'Multigrain Roti', servingSize: 1, servingUnit: 'piece (50g)', calories: 130, protein: 4.5, carbs: 22.0, fats: 2.0, category: 'Bread' },
  { name: 'Bajari Thepla', servingSize: 1, servingUnit: 'piece (50g)', calories: 135, protein: 3.5, carbs: 19.0, fats: 5.0, category: 'Bread' },
  { name: 'Kuttu Roti', servingSize: 1, servingUnit: 'piece (50g)', calories: 140, protein: 3.2, carbs: 24.0, fats: 2.5, category: 'Bread' },
  { name: 'Singhara Roti', servingSize: 1, servingUnit: 'piece (50g)', calories: 130, protein: 2.5, carbs: 26.0, fats: 2.0, category: 'Bread' },
  { name: 'Paneer Kulcha', servingSize: 1, servingUnit: 'piece (100g)', calories: 290, protein: 11.0, carbs: 38.0, fats: 10.0, category: 'Bread' },
  { name: 'Masala Roti', servingSize: 1, servingUnit: 'piece (50g)', calories: 130, protein: 3.5, carbs: 20.0, fats: 3.5, category: 'Bread' },
  { name: 'Sheermal', servingSize: 1, servingUnit: 'piece (80g)', calories: 280, protein: 6.0, carbs: 44.0, fats: 9.0, category: 'Bread' },
  { name: 'Kachori Roti', servingSize: 1, servingUnit: 'piece (50g)', calories: 160, protein: 3.0, carbs: 22.0, fats: 7.0, category: 'Bread' },
  { name: 'Puran Poli', servingSize: 1, servingUnit: 'piece (100g)', calories: 300, protein: 6.0, carbs: 54.0, fats: 7.0, category: 'Bread' },
  { name: 'Millet Roti', servingSize: 1, servingUnit: 'piece (50g)', calories: 125, protein: 3.5, carbs: 22.0, fats: 2.0, category: 'Bread' },

  // ═══════════════════════════════════════════════
  // RICE & GRAINS
  // ═══════════════════════════════════════════════
  { name: 'Steamed Basmati Rice', servingSize: 1, servingUnit: 'cup cooked (180g)', calories: 210, protein: 4.5, carbs: 46.0, fats: 0.5, category: 'Rice & Grains' },
  { name: 'Plain Rice (White)', servingSize: 1, servingUnit: 'cup cooked (180g)', calories: 206, protein: 4.3, carbs: 45.0, fats: 0.4, category: 'Rice & Grains' },
  { name: 'Brown Rice', servingSize: 1, servingUnit: 'cup cooked (195g)', calories: 216, protein: 5.0, carbs: 45.0, fats: 1.8, category: 'Rice & Grains' },
  { name: 'Jeera Rice', servingSize: 1, servingUnit: 'cup (200g)', calories: 240, protein: 5.0, carbs: 44.0, fats: 5.0, category: 'Rice & Grains' },
  { name: 'Veg Biryani', servingSize: 1, servingUnit: 'plate (250g)', calories: 350, protein: 8.0, carbs: 55.0, fats: 10.0, category: 'Rice & Grains' },
  { name: 'Chicken Biryani', servingSize: 1, servingUnit: 'plate (300g)', calories: 490, protein: 22.0, carbs: 55.0, fats: 18.0, category: 'Rice & Grains' },
  { name: 'Mutton Biryani', servingSize: 1, servingUnit: 'plate (300g)', calories: 520, protein: 24.0, carbs: 52.0, fats: 22.0, category: 'Rice & Grains' },
  { name: 'Egg Biryani', servingSize: 1, servingUnit: 'plate (280g)', calories: 420, protein: 16.0, carbs: 54.0, fats: 14.0, category: 'Rice & Grains' },
  { name: 'Veg Pulao', servingSize: 1, servingUnit: 'cup (200g)', calories: 260, protein: 5.5, carbs: 42.0, fats: 8.0, category: 'Rice & Grains' },
  { name: 'Peas Pulao', servingSize: 1, servingUnit: 'cup (200g)', calories: 250, protein: 6.0, carbs: 40.0, fats: 7.0, category: 'Rice & Grains' },
  { name: 'Lemon Rice', servingSize: 1, servingUnit: 'cup (200g)', calories: 230, protein: 4.5, carbs: 42.0, fats: 5.0, category: 'Rice & Grains' },
  { name: 'Curd Rice', servingSize: 1, servingUnit: 'cup (200g)', calories: 210, protein: 6.0, carbs: 38.0, fats: 4.0, category: 'Rice & Grains' },
  { name: 'Tomato Rice', servingSize: 1, servingUnit: 'cup (200g)', calories: 235, protein: 4.5, carbs: 42.0, fats: 5.5, category: 'Rice & Grains' },
  { name: 'Tamarind Rice', servingSize: 1, servingUnit: 'cup (200g)', calories: 245, protein: 4.0, carbs: 44.0, fats: 6.0, category: 'Rice & Grains' },
  { name: 'Coconut Rice', servingSize: 1, servingUnit: 'cup (200g)', calories: 280, protein: 4.5, carbs: 40.0, fats: 12.0, category: 'Rice & Grains' },
  { name: 'Khichdi (Moong Dal)', servingSize: 1, servingUnit: 'bowl (250g)', calories: 230, protein: 8.0, carbs: 38.0, fats: 5.0, category: 'Rice & Grains' },
  { name: 'Daliya (Broken Wheat)', servingSize: 1, servingUnit: 'bowl (200g)', calories: 150, protein: 5.0, carbs: 30.0, fats: 1.0, category: 'Rice & Grains' },
  { name: 'Oats Porridge', servingSize: 1, servingUnit: 'bowl (200g)', calories: 160, protein: 5.5, carbs: 28.0, fats: 3.0, category: 'Rice & Grains' },
  { name: 'Semiya Upma', servingSize: 1, servingUnit: 'plate (200g)', calories: 220, protein: 5.0, carbs: 35.0, fats: 7.0, category: 'Rice & Grains' },
  { name: 'Rava Upma', servingSize: 1, servingUnit: 'plate (200g)', calories: 210, protein: 5.0, carbs: 35.0, fats: 6.0, category: 'Rice & Grains' },
  { name: 'Sabudana Khichdi', servingSize: 1, servingUnit: 'plate (200g)', calories: 280, protein: 4.0, carbs: 45.0, fats: 10.0, category: 'Rice & Grains' },
  { name: 'Brown Rice Khichdi', servingSize: 1, servingUnit: 'bowl (250g)', calories: 210, protein: 7.0, carbs: 36.0, fats: 4.0, category: 'Rice & Grains' },
  { name: 'Saffron Rice', servingSize: 1, servingUnit: 'cup (200g)', calories: 225, protein: 4.5, carbs: 46.0, fats: 2.5, category: 'Rice & Grains' },
  { name: 'Millet Khichdi', servingSize: 1, servingUnit: 'bowl (250g)', calories: 195, protein: 6.5, carbs: 34.0, fats: 3.5, category: 'Rice & Grains' },
  { name: 'Curry Leaf Rice', servingSize: 1, servingUnit: 'cup (200g)', calories: 230, protein: 4.5, carbs: 43.0, fats: 4.5, category: 'Rice & Grains' },
  { name: 'Schezwan Fried Rice', servingSize: 1, servingUnit: 'plate (250g)', calories: 360, protein: 6.5, carbs: 52.0, fats: 14.0, category: 'Rice & Grains' },
  { name: 'Broken Wheat Upma', servingSize: 1, servingUnit: 'plate (200g)', calories: 180, protein: 6.0, carbs: 32.0, fats: 3.5, category: 'Rice & Grains' },
  { name: 'Jowar Upma', servingSize: 1, servingUnit: 'plate (200g)', calories: 175, protein: 5.5, carbs: 30.0, fats: 3.0, category: 'Rice & Grains' },
  { name: 'Oats Upma', servingSize: 1, servingUnit: 'plate (200g)', calories: 190, protein: 6.5, carbs: 29.0, fats: 5.0, category: 'Rice & Grains' },
  { name: 'Quinoa Pulao', servingSize: 1, servingUnit: 'cup (200g)', calories: 210, protein: 7.5, carbs: 32.0, fats: 5.0, category: 'Rice & Grains' },
  { name: 'Ragi Mudde', servingSize: 1, servingUnit: 'ball (150g)', calories: 300, protein: 7.0, carbs: 65.0, fats: 1.5, category: 'Rice & Grains' },
  { name: 'Brown Rice Biryani', servingSize: 1, servingUnit: 'plate (250g)', calories: 310, protein: 8.5, carbs: 50.0, fats: 9.0, category: 'Rice & Grains' },
  { name: 'Quinoa Biryani', servingSize: 1, servingUnit: 'plate (250g)', calories: 290, protein: 11.0, carbs: 45.0, fats: 8.0, category: 'Rice & Grains' },
  { name: 'Millet Biryani', servingSize: 1, servingUnit: 'plate (250g)', calories: 280, protein: 8.0, carbs: 48.0, fats: 7.5, category: 'Rice & Grains' },
  { name: 'Tomato Bath', servingSize: 1, servingUnit: 'plate (200g)', calories: 240, protein: 5.0, carbs: 42.0, fats: 6.0, category: 'Rice & Grains' },
  { name: 'Vangi Bath (Brinjal Rice)', servingSize: 1, servingUnit: 'plate (200g)', calories: 250, protein: 4.8, carbs: 43.0, fats: 7.0, category: 'Rice & Grains' },
  { name: 'Bisi Bele Bath', servingSize: 1, servingUnit: 'plate (250g)', calories: 290, protein: 8.0, carbs: 45.0, fats: 9.0, category: 'Rice & Grains' },
  { name: 'Puliyogare', servingSize: 1, servingUnit: 'plate (200g)', calories: 260, protein: 4.5, carbs: 44.0, fats: 8.0, category: 'Rice & Grains' },
  { name: 'Kashmiri Pulao', servingSize: 1, servingUnit: 'plate (250g)', calories: 320, protein: 6.5, carbs: 50.0, fats: 11.0, category: 'Rice & Grains' },
  { name: 'Capsicum Rice', servingSize: 1, servingUnit: 'plate (200g)', calories: 230, protein: 4.5, carbs: 40.0, fats: 6.0, category: 'Rice & Grains' },
  { name: 'Mint Rice (Pudina Rice)', servingSize: 1, servingUnit: 'plate (200g)', calories: 220, protein: 4.2, carbs: 40.0, fats: 5.5, category: 'Rice & Grains' },

  // ═══════════════════════════════════════════════
  // DALS & LENTILS
  // ═══════════════════════════════════════════════
  { name: 'Toor Dal (Arhar)', servingSize: 1, servingUnit: 'katori (150g)', calories: 160, protein: 10.0, carbs: 26.0, fats: 2.0, category: 'Dal & Lentils' },
  { name: 'Moong Dal (Yellow)', servingSize: 1, servingUnit: 'katori (150g)', calories: 145, protein: 9.0, carbs: 24.0, fats: 1.5, category: 'Dal & Lentils' },
  { name: 'Moong Dal (Green Whole)', servingSize: 1, servingUnit: 'katori (150g)', calories: 155, protein: 10.0, carbs: 25.0, fats: 1.5, category: 'Dal & Lentils' },
  { name: 'Masoor Dal', servingSize: 1, servingUnit: 'katori (150g)', calories: 150, protein: 9.5, carbs: 25.0, fats: 1.0, category: 'Dal & Lentils' },
  { name: 'Chana Dal', servingSize: 1, servingUnit: 'katori (150g)', calories: 170, protein: 10.0, carbs: 28.0, fats: 2.5, category: 'Dal & Lentils' },
  { name: 'Urad Dal', servingSize: 1, servingUnit: 'katori (150g)', calories: 165, protein: 10.5, carbs: 26.0, fats: 2.0, category: 'Dal & Lentils' },
  { name: 'Dal Tadka', servingSize: 1, servingUnit: 'katori (150g)', calories: 160, protein: 8.0, carbs: 20.0, fats: 7.0, category: 'Dal & Lentils' },
  { name: 'Dal Fry', servingSize: 1, servingUnit: 'katori (150g)', calories: 175, protein: 9.0, carbs: 22.0, fats: 6.5, category: 'Dal & Lentils' },
  { name: 'Dal Makhani', servingSize: 1, servingUnit: 'katori (200g)', calories: 250, protein: 10.0, carbs: 28.0, fats: 12.0, category: 'Dal & Lentils' },
  { name: 'Rajma (Kidney Beans)', servingSize: 1, servingUnit: 'katori (200g)', calories: 225, protein: 15.0, carbs: 40.0, fats: 1.0, category: 'Dal & Lentils' },
  { name: 'Chole (Chickpea Curry)', servingSize: 1, servingUnit: 'katori (200g)', calories: 269, protein: 15.0, carbs: 45.0, fats: 4.0, category: 'Dal & Lentils' },
  { name: 'Lobhia (Black-Eyed Peas)', servingSize: 1, servingUnit: 'katori (200g)', calories: 200, protein: 13.0, carbs: 35.0, fats: 1.0, category: 'Dal & Lentils' },
  { name: 'Sambhar', servingSize: 1, servingUnit: 'katori (200g)', calories: 130, protein: 6.0, carbs: 18.0, fats: 4.0, category: 'Dal & Lentils' },
  { name: 'Rasam', servingSize: 1, servingUnit: 'katori (150g)', calories: 50, protein: 2.0, carbs: 8.0, fats: 1.0, category: 'Dal & Lentils' },
  { name: 'Panchmel Dal', servingSize: 1, servingUnit: 'katori (150g)', calories: 165, protein: 9.5, carbs: 24.0, fats: 4.0, category: 'Dal & Lentils' },
  { name: 'Kadhi (Besan)', servingSize: 1, servingUnit: 'katori (200g)', calories: 140, protein: 5.0, carbs: 12.0, fats: 8.0, category: 'Dal & Lentils' },
  { name: 'Kadhi Pakora', servingSize: 1, servingUnit: 'katori (250g)', calories: 220, protein: 6.0, carbs: 18.0, fats: 14.0, category: 'Dal & Lentils' },
  { name: 'Sprouted Moong Curry', servingSize: 1, servingUnit: 'katori (150g)', calories: 130, protein: 8.0, carbs: 20.0, fats: 2.0, category: 'Dal & Lentils' },
  { name: 'Chana Masala (Dry)', servingSize: 1, servingUnit: 'katori (150g)', calories: 180, protein: 9.0, carbs: 26.0, fats: 4.5, category: 'Dal & Lentils' },
  { name: 'Rajma Masala (Dry)', servingSize: 1, servingUnit: 'katori (150g)', calories: 190, protein: 10.0, carbs: 28.0, fats: 4.0, category: 'Dal & Lentils' },
  { name: 'Moong Dal Tadka', servingSize: 1, servingUnit: 'katori (150g)', calories: 150, protein: 8.5, carbs: 22.0, fats: 4.0, category: 'Dal & Lentils' },
  { name: 'Urad Dal Tadka', servingSize: 1, servingUnit: 'katori (150g)', calories: 160, protein: 9.5, carbs: 23.0, fats: 4.5, category: 'Dal & Lentils' },
  { name: 'Kulthi Dal (Horse Gram)', servingSize: 1, servingUnit: 'katori (150g)', calories: 140, protein: 11.0, carbs: 22.0, fats: 1.5, category: 'Dal & Lentils' },
  { name: 'Moth Dal', servingSize: 1, servingUnit: 'katori (150g)', calories: 150, protein: 10.0, carbs: 24.0, fats: 2.0, category: 'Dal & Lentils' },
  { name: 'Lobiya Masala', servingSize: 1, servingUnit: 'katori (150g)', calories: 160, protein: 10.5, carbs: 25.0, fats: 3.0, category: 'Dal & Lentils' },
  { name: 'Gahat Dal', servingSize: 1, servingUnit: 'katori (150g)', calories: 135, protein: 9.5, carbs: 22.0, fats: 1.5, category: 'Dal & Lentils' },
  { name: 'Dal Maharani', servingSize: 1, servingUnit: 'katori (150g)', calories: 210, protein: 9.0, carbs: 24.0, fats: 9.0, category: 'Dal & Lentils' },
  { name: 'Sindhi Kadhi', servingSize: 1, servingUnit: 'katori (200g)', calories: 150, protein: 4.0, carbs: 18.0, fats: 7.0, category: 'Dal & Lentils' },
  { name: 'Chana Dal with Lauki', servingSize: 1, servingUnit: 'katori (150g)', calories: 145, protein: 8.0, carbs: 22.0, fats: 3.5, category: 'Dal & Lentils' },
  { name: 'Black Masoor Dal', servingSize: 1, servingUnit: 'katori (150g)', calories: 140, protein: 9.0, carbs: 24.0, fats: 1.2, category: 'Dal & Lentils' },
  { name: 'Yellow Moong Dal (Dry)', servingSize: 1, servingUnit: 'katori (150g)', calories: 160, protein: 10.0, carbs: 26.0, fats: 2.5, category: 'Dal & Lentils' },
  { name: 'Dal Kabila', servingSize: 1, servingUnit: 'katori (150g)', calories: 170, protein: 9.0, carbs: 23.0, fats: 5.5, category: 'Dal & Lentils' },
  { name: 'Dal Banjara', servingSize: 1, servingUnit: 'katori (150g)', calories: 165, protein: 9.2, carbs: 22.0, fats: 5.0, category: 'Dal & Lentils' },
  { name: 'Dal Panchratna', servingSize: 1, servingUnit: 'katori (150g)', calories: 180, protein: 11.0, carbs: 25.0, fats: 5.0, category: 'Dal & Lentils' },
  { name: 'Gujarati Dal', servingSize: 1, servingUnit: 'katori (150g)', calories: 150, protein: 7.5, carbs: 24.0, fats: 3.5, category: 'Dal & Lentils' },

  // ═══════════════════════════════════════════════
  // VEGETABLE CURRIES
  // ═══════════════════════════════════════════════
  { name: 'Aloo Gobi', servingSize: 1, servingUnit: 'katori (200g)', calories: 180, protein: 4.0, carbs: 22.0, fats: 9.0, category: 'Vegetable Curry' },
  { name: 'Palak Paneer', servingSize: 1, servingUnit: 'katori (200g)', calories: 250, protein: 12.0, carbs: 10.0, fats: 18.0, category: 'Vegetable Curry' },
  { name: 'Shahi Paneer', servingSize: 1, servingUnit: 'katori (200g)', calories: 310, protein: 14.0, carbs: 12.0, fats: 24.0, category: 'Vegetable Curry' },
  { name: 'Paneer Butter Masala', servingSize: 1, servingUnit: 'katori (200g)', calories: 330, protein: 14.0, carbs: 14.0, fats: 25.0, category: 'Vegetable Curry' },
  { name: 'Paneer Tikka Masala', servingSize: 1, servingUnit: 'katori (200g)', calories: 290, protein: 15.0, carbs: 12.0, fats: 20.0, category: 'Vegetable Curry' },
  { name: 'Kadai Paneer', servingSize: 1, servingUnit: 'katori (200g)', calories: 280, protein: 14.0, carbs: 10.0, fats: 20.0, category: 'Vegetable Curry' },
  { name: 'Matar Paneer', servingSize: 1, servingUnit: 'katori (200g)', calories: 270, protein: 13.0, carbs: 14.0, fats: 18.0, category: 'Vegetable Curry' },
  { name: 'Bhindi Masala', servingSize: 1, servingUnit: 'katori (150g)', calories: 120, protein: 3.0, carbs: 10.0, fats: 8.0, category: 'Vegetable Curry' },
  { name: 'Baingan Bharta', servingSize: 1, servingUnit: 'katori (200g)', calories: 140, protein: 3.5, carbs: 12.0, fats: 9.0, category: 'Vegetable Curry' },
  { name: 'Aloo Matar', servingSize: 1, servingUnit: 'katori (200g)', calories: 190, protein: 5.0, carbs: 28.0, fats: 7.0, category: 'Vegetable Curry' },
  { name: 'Aloo Jeera', servingSize: 1, servingUnit: 'katori (200g)', calories: 180, protein: 3.5, carbs: 26.0, fats: 7.0, category: 'Vegetable Curry' },
  { name: 'Aloo Palak', servingSize: 1, servingUnit: 'katori (200g)', calories: 170, protein: 4.0, carbs: 22.0, fats: 8.0, category: 'Vegetable Curry' },
  { name: 'Mix Veg Curry', servingSize: 1, servingUnit: 'katori (200g)', calories: 160, protein: 4.0, carbs: 18.0, fats: 8.0, category: 'Vegetable Curry' },
  { name: 'Lauki Ki Sabzi', servingSize: 1, servingUnit: 'katori (200g)', calories: 90, protein: 2.0, carbs: 12.0, fats: 4.0, category: 'Vegetable Curry' },
  { name: 'Tinda Masala', servingSize: 1, servingUnit: 'katori (200g)', calories: 100, protein: 2.5, carbs: 14.0, fats: 4.0, category: 'Vegetable Curry' },
  { name: 'Tori Ki Sabzi', servingSize: 1, servingUnit: 'katori (200g)', calories: 85, protein: 2.0, carbs: 10.0, fats: 4.0, category: 'Vegetable Curry' },
  { name: 'Karela Sabzi', servingSize: 1, servingUnit: 'katori (150g)', calories: 80, protein: 2.0, carbs: 8.0, fats: 5.0, category: 'Vegetable Curry' },
  { name: 'Gobi Manchurian', servingSize: 1, servingUnit: 'plate (200g)', calories: 280, protein: 5.0, carbs: 30.0, fats: 15.0, category: 'Vegetable Curry' },
  { name: 'Malai Kofta', servingSize: 1, servingUnit: 'katori (200g)', calories: 350, protein: 8.0, carbs: 20.0, fats: 26.0, category: 'Vegetable Curry' },
  { name: 'Dum Aloo', servingSize: 1, servingUnit: 'katori (200g)', calories: 250, protein: 5.0, carbs: 30.0, fats: 12.0, category: 'Vegetable Curry' },
  { name: 'Navratan Korma', servingSize: 1, servingUnit: 'katori (200g)', calories: 300, protein: 7.0, carbs: 22.0, fats: 20.0, category: 'Vegetable Curry' },
  { name: 'Sarson Ka Saag', servingSize: 1, servingUnit: 'katori (200g)', calories: 130, protein: 4.0, carbs: 8.0, fats: 10.0, category: 'Vegetable Curry' },
  { name: 'Methi Aloo', servingSize: 1, servingUnit: 'katori (200g)', calories: 170, protein: 4.0, carbs: 24.0, fats: 7.0, category: 'Vegetable Curry' },
  { name: 'Sem Ki Sabzi', servingSize: 1, servingUnit: 'katori (150g)', calories: 100, protein: 3.5, carbs: 14.0, fats: 4.0, category: 'Vegetable Curry' },
  { name: 'Cabbage Sabzi', servingSize: 1, servingUnit: 'katori (150g)', calories: 80, protein: 2.0, carbs: 10.0, fats: 4.0, category: 'Vegetable Curry' },
  { name: 'Arbi Masala', servingSize: 1, servingUnit: 'katori (200g)', calories: 200, protein: 3.0, carbs: 30.0, fats: 8.0, category: 'Vegetable Curry' },
  { name: 'Jackfruit Curry (Kathal)', servingSize: 1, servingUnit: 'katori (200g)', calories: 180, protein: 4.0, carbs: 28.0, fats: 6.0, category: 'Vegetable Curry' },
  { name: 'Mushroom Masala', servingSize: 1, servingUnit: 'katori (200g)', calories: 150, protein: 5.0, carbs: 12.0, fats: 9.0, category: 'Vegetable Curry' },
  { name: 'Mushroom Matar', servingSize: 1, servingUnit: 'katori (200g)', calories: 160, protein: 6.0, carbs: 14.0, fats: 9.0, category: 'Vegetable Curry' },
  { name: 'Paneer Bhurji', servingSize: 1, servingUnit: 'katori (150g)', calories: 250, protein: 14.0, carbs: 6.0, fats: 19.0, category: 'Vegetable Curry' },
  { name: 'Undhiyu', servingSize: 1, servingUnit: 'katori (200g)', calories: 220, protein: 5.0, carbs: 25.0, fats: 12.0, category: 'Vegetable Curry' },
  { name: 'Aviyal', servingSize: 1, servingUnit: 'katori (200g)', calories: 170, protein: 3.5, carbs: 15.0, fats: 11.0, category: 'Vegetable Curry' },
  { name: 'Kootu Curry', servingSize: 1, servingUnit: 'katori (200g)', calories: 140, protein: 6.0, carbs: 18.0, fats: 5.0, category: 'Vegetable Curry' },
  { name: 'Aloo Baingan', servingSize: 1, servingUnit: 'katori (150g)', calories: 130, protein: 2.5, carbs: 16.0, fats: 6.0, category: 'Vegetable Curry' },
  { name: 'Aloo Methi', servingSize: 1, servingUnit: 'katori (150g)', calories: 140, protein: 3.0, carbs: 18.0, fats: 6.0, category: 'Vegetable Curry' },
  { name: 'Aloo Beans', servingSize: 1, servingUnit: 'katori (150g)', calories: 125, protein: 2.8, carbs: 15.0, fats: 5.5, category: 'Vegetable Curry' },
  { name: 'Aloo Shimla Mirch', servingSize: 1, servingUnit: 'katori (150g)', calories: 130, protein: 2.5, carbs: 16.0, fats: 6.0, category: 'Vegetable Curry' },
  { name: 'Bhindi Fry', servingSize: 1, servingUnit: 'katori (150g)', calories: 140, protein: 2.5, carbs: 12.0, fats: 9.0, category: 'Vegetable Curry' },
  { name: 'Baingan Masala', servingSize: 1, servingUnit: 'katori (150g)', calories: 150, protein: 3.0, carbs: 14.0, fats: 9.0, category: 'Vegetable Curry' },
  { name: 'Gobi Matar Masala', servingSize: 1, servingUnit: 'katori (150g)', calories: 140, protein: 4.0, carbs: 15.0, fats: 7.0, category: 'Vegetable Curry' },
  { name: 'Patta Gobi Matar', servingSize: 1, servingUnit: 'katori (150g)', calories: 110, protein: 3.0, carbs: 12.0, fats: 5.0, category: 'Vegetable Curry' },
  { name: 'Lauki Kofta Curry', servingSize: 1, servingUnit: 'katori (200g)', calories: 220, protein: 6.0, carbs: 18.0, fats: 14.0, category: 'Vegetable Curry' },
  { name: 'Kathal Masala (Jackfruit)', servingSize: 1, servingUnit: 'katori (150g)', calories: 160, protein: 3.5, carbs: 22.0, fats: 6.0, category: 'Vegetable Curry' },
  { name: 'Kadhi Bari', servingSize: 1, servingUnit: 'katori (200g)', calories: 180, protein: 7.0, carbs: 20.0, fats: 8.0, category: 'Vegetable Curry' },
  { name: 'Palak Corn', servingSize: 1, servingUnit: 'katori (150g)', calories: 160, protein: 5.0, carbs: 14.0, fats: 9.0, category: 'Vegetable Curry' },
  { name: 'Methi Chaman', servingSize: 1, servingUnit: 'katori (150g)', calories: 210, protein: 9.0, carbs: 10.0, fats: 15.0, category: 'Vegetable Curry' },
  { name: 'Paneer Pasanda', servingSize: 1, servingUnit: 'katori (200g)', calories: 320, protein: 13.0, carbs: 12.0, fats: 25.0, category: 'Vegetable Curry' },
  { name: 'Veg Jalfrezi', servingSize: 1, servingUnit: 'katori (150g)', calories: 150, protein: 3.5, carbs: 14.0, fats: 9.0, category: 'Vegetable Curry' },

  // ═══════════════════════════════════════════════
  // NON-VEG CURRIES & DISHES
  // ═══════════════════════════════════════════════
  { name: 'Chicken Curry (Home Style)', servingSize: 1, servingUnit: 'katori (200g)', calories: 260, protein: 22.0, carbs: 8.0, fats: 16.0, category: 'Non-Veg' },
  { name: 'Butter Chicken', servingSize: 1, servingUnit: 'katori (200g)', calories: 340, protein: 20.0, carbs: 12.0, fats: 24.0, category: 'Non-Veg' },
  { name: 'Chicken Tikka Masala', servingSize: 1, servingUnit: 'katori (200g)', calories: 300, protein: 22.0, carbs: 10.0, fats: 20.0, category: 'Non-Veg' },
  { name: 'Tandoori Chicken', servingSize: 1, servingUnit: 'leg piece (150g)', calories: 220, protein: 28.0, carbs: 4.0, fats: 10.0, category: 'Non-Veg' },
  { name: 'Chicken Tikka', servingSize: 6, servingUnit: 'pieces (150g)', calories: 200, protein: 30.0, carbs: 4.0, fats: 7.0, category: 'Non-Veg' },
  { name: 'Chicken Korma', servingSize: 1, servingUnit: 'katori (200g)', calories: 350, protein: 20.0, carbs: 10.0, fats: 26.0, category: 'Non-Veg' },
  { name: 'Chicken Keema', servingSize: 1, servingUnit: 'katori (200g)', calories: 280, protein: 24.0, carbs: 6.0, fats: 18.0, category: 'Non-Veg' },
  { name: 'Kadai Chicken', servingSize: 1, servingUnit: 'katori (200g)', calories: 290, protein: 22.0, carbs: 8.0, fats: 19.0, category: 'Non-Veg' },
  { name: 'Chicken Do Pyaza', servingSize: 1, servingUnit: 'katori (200g)', calories: 270, protein: 22.0, carbs: 10.0, fats: 16.0, category: 'Non-Veg' },
  { name: 'Chicken Breast (Grilled)', servingSize: 100, servingUnit: 'grams', calories: 165, protein: 31.0, carbs: 0.0, fats: 3.6, category: 'Non-Veg' },
  { name: 'Mutton Curry', servingSize: 1, servingUnit: 'katori (200g)', calories: 350, protein: 24.0, carbs: 8.0, fats: 25.0, category: 'Non-Veg' },
  { name: 'Mutton Rogan Josh', servingSize: 1, servingUnit: 'katori (200g)', calories: 330, protein: 25.0, carbs: 6.0, fats: 23.0, category: 'Non-Veg' },
  { name: 'Keema Matar', servingSize: 1, servingUnit: 'katori (200g)', calories: 300, protein: 22.0, carbs: 12.0, fats: 18.0, category: 'Non-Veg' },
  { name: 'Mutton Nihari', servingSize: 1, servingUnit: 'bowl (250g)', calories: 420, protein: 28.0, carbs: 10.0, fats: 30.0, category: 'Non-Veg' },
  { name: 'Fish Curry (Home Style)', servingSize: 1, servingUnit: 'katori (200g)', calories: 200, protein: 20.0, carbs: 6.0, fats: 10.0, category: 'Non-Veg' },
  { name: 'Fish Fry', servingSize: 1, servingUnit: 'piece (100g)', calories: 190, protein: 18.0, carbs: 8.0, fats: 10.0, category: 'Non-Veg' },
  { name: 'Prawn Curry', servingSize: 1, servingUnit: 'katori (200g)', calories: 220, protein: 22.0, carbs: 6.0, fats: 12.0, category: 'Non-Veg' },
  { name: 'Egg Curry', servingSize: 1, servingUnit: 'katori (200g)', calories: 230, protein: 14.0, carbs: 8.0, fats: 16.0, category: 'Non-Veg' },
  { name: 'Egg Bhurji', servingSize: 1, servingUnit: 'plate (150g)', calories: 200, protein: 14.0, carbs: 4.0, fats: 14.0, category: 'Non-Veg' },
  { name: 'Boiled Egg', servingSize: 1, servingUnit: 'piece (50g)', calories: 78, protein: 6.0, carbs: 0.6, fats: 5.0, category: 'Non-Veg' },
  { name: 'Omelette (2 Eggs)', servingSize: 1, servingUnit: 'serving (120g)', calories: 190, protein: 13.0, carbs: 2.0, fats: 14.0, category: 'Non-Veg' },
  { name: 'Chicken Seekh Kebab', servingSize: 2, servingUnit: 'pieces (100g)', calories: 180, protein: 20.0, carbs: 4.0, fats: 9.0, category: 'Non-Veg' },
  { name: 'Chicken 65', servingSize: 1, servingUnit: 'plate (150g)', calories: 280, protein: 20.0, carbs: 15.0, fats: 16.0, category: 'Non-Veg' },
  { name: 'Chettinad Chicken', servingSize: 1, servingUnit: 'katori (200g)', calories: 290, protein: 22.0, carbs: 8.0, fats: 18.0, category: 'Non-Veg' },
  { name: 'Chicken Chettinad', servingSize: 1, servingUnit: 'katori (200g)', calories: 270, protein: 24.0, carbs: 7.0, fats: 16.0, category: 'Non-Veg' },
  { name: 'Chicken Saagwala', servingSize: 1, servingUnit: 'katori (200g)', calories: 240, protein: 25.0, carbs: 6.0, fats: 13.0, category: 'Non-Veg' },
  { name: 'Chicken Kadhai', servingSize: 1, servingUnit: 'katori (200g)', calories: 280, protein: 23.0, carbs: 8.0, fats: 17.0, category: 'Non-Veg' },
  { name: 'Mutton Korma', servingSize: 1, servingUnit: 'katori (200g)', calories: 360, protein: 23.0, carbs: 9.0, fats: 26.0, category: 'Non-Veg' },
  { name: 'Mutton Bhuna', servingSize: 1, servingUnit: 'katori (200g)', calories: 340, protein: 26.0, carbs: 7.0, fats: 23.0, category: 'Non-Veg' },
  { name: 'Fish Amritsari', servingSize: 1, servingUnit: 'plate (150g)', calories: 250, protein: 22.0, carbs: 10.0, fats: 13.0, category: 'Non-Veg' },
  { name: 'Prawn Balchao', servingSize: 1, servingUnit: 'katori (150g)', calories: 210, protein: 20.0, carbs: 8.0, fats: 11.0, category: 'Non-Veg' },
  { name: 'Egg Masala', servingSize: 1, servingUnit: 'katori (200g)', calories: 220, protein: 13.5, carbs: 7.0, fats: 15.0, category: 'Non-Veg' },
  { name: 'Chicken Seekh Roll', servingSize: 1, servingUnit: 'roll (200g)', calories: 340, protein: 22.0, carbs: 32.0, fats: 14.0, category: 'Non-Veg' },
  { name: 'Mutton Seekh Kebab', servingSize: 2, servingUnit: 'pieces (100g)', calories: 210, protein: 22.0, carbs: 3.0, fats: 12.0, category: 'Non-Veg' },

  // ═══════════════════════════════════════════════
  // BREAKFAST ITEMS
  // ═══════════════════════════════════════════════
  { name: 'Idli', servingSize: 2, servingUnit: 'pieces (120g)', calories: 156, protein: 4.0, carbs: 34.0, fats: 0.4, category: 'Breakfast' },
  { name: 'Plain Dosa', servingSize: 1, servingUnit: 'piece (120g)', calories: 168, protein: 4.0, carbs: 28.0, fats: 4.0, category: 'Breakfast' },
  { name: 'Masala Dosa', servingSize: 1, servingUnit: 'piece (200g)', calories: 280, protein: 6.0, carbs: 40.0, fats: 10.0, category: 'Breakfast' },
  { name: 'Rava Dosa', servingSize: 1, servingUnit: 'piece (150g)', calories: 210, protein: 4.0, carbs: 30.0, fats: 8.0, category: 'Breakfast' },
  { name: 'Onion Dosa', servingSize: 1, servingUnit: 'piece (150g)', calories: 220, protein: 5.0, carbs: 32.0, fats: 8.0, category: 'Breakfast' },
  { name: 'Uttapam', servingSize: 1, servingUnit: 'piece (150g)', calories: 200, protein: 5.0, carbs: 34.0, fats: 5.0, category: 'Breakfast' },
  { name: 'Medu Vada', servingSize: 2, servingUnit: 'pieces (80g)', calories: 200, protein: 6.0, carbs: 22.0, fats: 10.0, category: 'Breakfast' },
  { name: 'Poha (Flattened Rice)', servingSize: 1, servingUnit: 'plate (200g)', calories: 250, protein: 5.0, carbs: 40.0, fats: 8.0, category: 'Breakfast' },
  { name: 'Upma (Suji)', servingSize: 1, servingUnit: 'plate (200g)', calories: 210, protein: 5.0, carbs: 35.0, fats: 6.0, category: 'Breakfast' },
  { name: 'Aloo Poha', servingSize: 1, servingUnit: 'plate (200g)', calories: 270, protein: 5.0, carbs: 42.0, fats: 9.0, category: 'Breakfast' },
  { name: 'Besan Cheela', servingSize: 2, servingUnit: 'pieces (120g)', calories: 200, protein: 8.0, carbs: 22.0, fats: 9.0, category: 'Breakfast' },
  { name: 'Moong Dal Cheela', servingSize: 2, servingUnit: 'pieces (120g)', calories: 180, protein: 10.0, carbs: 24.0, fats: 5.0, category: 'Breakfast' },
  { name: 'Pesarattu', servingSize: 1, servingUnit: 'piece (120g)', calories: 170, protein: 8.0, carbs: 26.0, fats: 4.0, category: 'Breakfast' },
  { name: 'Puttu', servingSize: 1, servingUnit: 'cylinder (150g)', calories: 230, protein: 4.0, carbs: 42.0, fats: 5.0, category: 'Breakfast' },
  { name: 'Pongal (Ven)', servingSize: 1, servingUnit: 'bowl (200g)', calories: 240, protein: 6.0, carbs: 38.0, fats: 7.0, category: 'Breakfast' },
  { name: 'Bread Toast with Butter', servingSize: 2, servingUnit: 'slices (60g)', calories: 200, protein: 4.0, carbs: 26.0, fats: 9.0, category: 'Breakfast' },
  { name: 'Bread Omelette', servingSize: 1, servingUnit: 'serving (150g)', calories: 280, protein: 14.0, carbs: 26.0, fats: 14.0, category: 'Breakfast' },
  { name: 'Puri Bhaji', servingSize: 1, servingUnit: 'plate (200g)', calories: 350, protein: 7.0, carbs: 42.0, fats: 16.0, category: 'Breakfast' },
  { name: 'Chole Bhature', servingSize: 1, servingUnit: 'plate (300g)', calories: 500, protein: 14.0, carbs: 60.0, fats: 22.0, category: 'Breakfast' },
  { name: 'Misal Pav', servingSize: 1, servingUnit: 'plate (300g)', calories: 400, protein: 14.0, carbs: 50.0, fats: 16.0, category: 'Breakfast' },
  { name: 'Sabudana Vada', servingSize: 2, servingUnit: 'pieces (80g)', calories: 220, protein: 3.0, carbs: 30.0, fats: 10.0, category: 'Breakfast' },
  { name: 'Cornflakes with Milk', servingSize: 1, servingUnit: 'bowl (250ml)', calories: 220, protein: 7.0, carbs: 38.0, fats: 4.0, category: 'Breakfast' },
  { name: 'Muesli with Milk', servingSize: 1, servingUnit: 'bowl (250ml)', calories: 280, protein: 8.0, carbs: 42.0, fats: 8.0, category: 'Breakfast' },
  { name: 'Set Dosa', servingSize: 2, servingUnit: 'pieces (120g)', calories: 180, protein: 4.5, carbs: 32.0, fats: 3.5, category: 'Breakfast' },
  { name: 'Neer Dosa', servingSize: 3, servingUnit: 'pieces (100g)', calories: 150, protein: 3.0, carbs: 30.0, fats: 2.0, category: 'Breakfast' },
  { name: 'Kanchipuram Idli', servingSize: 2, servingUnit: 'pieces (120g)', calories: 170, protein: 4.5, carbs: 30.0, fats: 3.5, category: 'Breakfast' },
  { name: 'Rava Idli', servingSize: 2, servingUnit: 'pieces (120g)', calories: 180, protein: 5.0, carbs: 32.0, fats: 3.0, category: 'Breakfast' },
  { name: 'Bread Upma', servingSize: 1, servingUnit: 'plate (150g)', calories: 220, protein: 5.0, carbs: 34.0, fats: 7.0, category: 'Breakfast' },
  { name: 'Vermicelli Kheer (Seviyan)', servingSize: 1, servingUnit: 'katori (150g)', calories: 210, protein: 5.0, carbs: 32.0, fats: 7.0, category: 'Breakfast' },
  { name: 'Sago Khichdi (Sabudana)', servingSize: 1, servingUnit: 'plate (200g)', calories: 290, protein: 3.5, carbs: 50.0, fats: 9.0, category: 'Breakfast' },
  { name: 'Chana Poori', servingSize: 1, servingUnit: 'plate (200g)', calories: 360, protein: 9.0, carbs: 48.0, fats: 15.0, category: 'Breakfast' },
  { name: 'Egg Appam', servingSize: 1, servingUnit: 'piece (90g)', calories: 160, protein: 8.5, carbs: 20.0, fats: 5.5, category: 'Breakfast' },

  // ═══════════════════════════════════════════════
  // SNACKS
  // ═══════════════════════════════════════════════
  { name: 'Samosa', servingSize: 1, servingUnit: 'piece (80g)', calories: 262, protein: 4.0, carbs: 24.0, fats: 17.0, category: 'Snack' },
  { name: 'Kachori', servingSize: 1, servingUnit: 'piece (60g)', calories: 230, protein: 4.0, carbs: 22.0, fats: 14.0, category: 'Snack' },
  { name: 'Aloo Tikki', servingSize: 1, servingUnit: 'piece (80g)', calories: 180, protein: 3.0, carbs: 22.0, fats: 9.0, category: 'Snack' },
  { name: 'Pakora (Mixed Veg)', servingSize: 5, servingUnit: 'pieces (100g)', calories: 250, protein: 5.0, carbs: 22.0, fats: 16.0, category: 'Snack' },
  { name: 'Onion Bhaji', servingSize: 4, servingUnit: 'pieces (80g)', calories: 200, protein: 4.0, carbs: 20.0, fats: 12.0, category: 'Snack' },
  { name: 'Paneer Pakora', servingSize: 4, servingUnit: 'pieces (100g)', calories: 280, protein: 12.0, carbs: 16.0, fats: 18.0, category: 'Snack' },
  { name: 'Vada Pav', servingSize: 1, servingUnit: 'piece (150g)', calories: 280, protein: 6.0, carbs: 38.0, fats: 12.0, category: 'Snack' },
  { name: 'Pav Bhaji', servingSize: 1, servingUnit: 'plate (300g)', calories: 400, protein: 10.0, carbs: 50.0, fats: 18.0, category: 'Snack' },
  { name: 'Bhel Puri', servingSize: 1, servingUnit: 'plate (150g)', calories: 180, protein: 4.0, carbs: 30.0, fats: 5.0, category: 'Snack' },
  { name: 'Sev Puri', servingSize: 6, servingUnit: 'pieces (120g)', calories: 200, protein: 4.0, carbs: 28.0, fats: 8.0, category: 'Snack' },
  { name: 'Pani Puri (Golgappa)', servingSize: 6, servingUnit: 'pieces (100g)', calories: 150, protein: 2.0, carbs: 28.0, fats: 4.0, category: 'Snack' },
  { name: 'Dahi Puri', servingSize: 6, servingUnit: 'pieces (150g)', calories: 220, protein: 5.0, carbs: 32.0, fats: 8.0, category: 'Snack' },
  { name: 'Ragda Pattice', servingSize: 1, servingUnit: 'plate (200g)', calories: 280, protein: 8.0, carbs: 38.0, fats: 10.0, category: 'Snack' },
  { name: 'Dabeli', servingSize: 1, servingUnit: 'piece (120g)', calories: 250, protein: 5.0, carbs: 35.0, fats: 10.0, category: 'Snack' },
  { name: 'Dhokla', servingSize: 4, servingUnit: 'pieces (120g)', calories: 160, protein: 6.0, carbs: 24.0, fats: 4.0, category: 'Snack' },
  { name: 'Khandvi', servingSize: 5, servingUnit: 'pieces (100g)', calories: 130, protein: 5.0, carbs: 18.0, fats: 4.0, category: 'Snack' },
  { name: 'Fafda', servingSize: 3, servingUnit: 'pieces (60g)', calories: 200, protein: 4.0, carbs: 24.0, fats: 10.0, category: 'Snack' },
  { name: 'Gathiya', servingSize: 50, servingUnit: 'grams', calories: 250, protein: 6.0, carbs: 22.0, fats: 16.0, category: 'Snack' },
  { name: 'Namkeen Mixture', servingSize: 30, servingUnit: 'grams', calories: 150, protein: 3.0, carbs: 16.0, fats: 8.0, category: 'Snack' },
  { name: 'Murukku', servingSize: 3, servingUnit: 'pieces (30g)', calories: 150, protein: 3.0, carbs: 18.0, fats: 7.0, category: 'Snack' },
  { name: 'Bonda', servingSize: 2, servingUnit: 'pieces (80g)', calories: 200, protein: 4.0, carbs: 24.0, fats: 10.0, category: 'Snack' },
  { name: 'Masala Peanuts', servingSize: 50, servingUnit: 'grams', calories: 280, protein: 12.0, carbs: 12.0, fats: 22.0, category: 'Snack' },
  { name: 'Roasted Chana', servingSize: 50, servingUnit: 'grams', calories: 180, protein: 10.0, carbs: 28.0, fats: 3.0, category: 'Snack' },
  { name: 'Makhana (Roasted)', servingSize: 30, servingUnit: 'grams', calories: 100, protein: 3.0, carbs: 18.0, fats: 0.5, category: 'Snack' },
  { name: 'Papad (Roasted)', servingSize: 1, servingUnit: 'piece (15g)', calories: 45, protein: 2.0, carbs: 7.0, fats: 1.0, category: 'Snack' },
  { name: 'Papad (Fried)', servingSize: 1, servingUnit: 'piece (15g)', calories: 75, protein: 2.0, carbs: 7.0, fats: 4.0, category: 'Snack' },
  { name: 'Mathri', servingSize: 3, servingUnit: 'pieces (30g)', calories: 150, protein: 2.0, carbs: 16.0, fats: 8.5, category: 'Snack' },
  { name: 'Banana Chips', servingSize: 30, servingUnit: 'grams', calories: 160, protein: 1.0, carbs: 18.0, fats: 10.0, category: 'Snack' },
  { name: 'Spring Roll (Veg)', servingSize: 2, servingUnit: 'pieces (100g)', calories: 220, protein: 4.0, carbs: 26.0, fats: 11.0, category: 'Snack' },
  { name: 'Momos (Veg)', servingSize: 6, servingUnit: 'pieces (150g)', calories: 220, protein: 6.0, carbs: 34.0, fats: 6.0, category: 'Snack' },
  { name: 'Momos (Chicken)', servingSize: 6, servingUnit: 'pieces (150g)', calories: 260, protein: 14.0, carbs: 30.0, fats: 8.0, category: 'Snack' },
  { name: 'Dhokla (Nylon)', servingSize: 4, servingUnit: 'pieces (120g)', calories: 150, protein: 5.5, carbs: 24.0, fats: 3.5, category: 'Snack' },
  { name: 'Methi Na Gotta', servingSize: 5, servingUnit: 'pieces (100g)', calories: 260, protein: 6.0, carbs: 28.0, fats: 14.0, category: 'Snack' },
  { name: 'Dal Vada', servingSize: 3, servingUnit: 'pieces (90g)', calories: 210, protein: 7.0, carbs: 22.0, fats: 10.0, category: 'Snack' },
  { name: 'Gobi Pakora', servingSize: 5, servingUnit: 'pieces (100g)', calories: 220, protein: 4.0, carbs: 20.0, fats: 14.0, category: 'Snack' },
  { name: 'Mirchi Vada', servingSize: 1, servingUnit: 'piece (80g)', calories: 190, protein: 3.5, carbs: 22.0, fats: 10.0, category: 'Snack' },
  { name: 'Kothimbir Vadi', servingSize: 4, servingUnit: 'pieces (100g)', calories: 180, protein: 5.0, carbs: 22.0, fats: 8.0, category: 'Snack' },
  { name: 'Alu Vadi', servingSize: 4, servingUnit: 'pieces (100g)', calories: 170, protein: 4.5, carbs: 24.0, fats: 6.0, category: 'Snack' },
  { name: 'Dry Kachori', servingSize: 2, servingUnit: 'pieces (40g)', calories: 160, protein: 2.5, carbs: 18.0, fats: 9.0, category: 'Snack' },
  { name: 'Maddur Vada', servingSize: 1, servingUnit: 'piece (60g)', calories: 210, protein: 4.0, carbs: 24.0, fats: 11.0, category: 'Snack' },
  { name: 'Bakarwadi', servingSize: 5, servingUnit: 'pieces (40g)', calories: 180, protein: 3.0, carbs: 22.0, fats: 9.0, category: 'Snack' },

  // ═══════════════════════════════════════════════
  // DAIRY
  // ═══════════════════════════════════════════════
  { name: 'Milk (Full Cream)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 160, protein: 8.0, carbs: 12.0, fats: 8.5, category: 'Dairy' },
  { name: 'Milk (Toned)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 120, protein: 8.0, carbs: 12.0, fats: 3.0, category: 'Dairy' },
  { name: 'Milk (Skimmed)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 85, protein: 8.5, carbs: 12.0, fats: 0.5, category: 'Dairy' },
  { name: 'Paneer (Fresh)', servingSize: 100, servingUnit: 'grams', calories: 265, protein: 18.0, carbs: 1.2, fats: 21.0, category: 'Dairy' },
  { name: 'Curd (Dahi)', servingSize: 1, servingUnit: 'katori (150g)', calories: 98, protein: 5.0, carbs: 8.0, fats: 5.0, category: 'Dairy' },
  { name: 'Low-Fat Curd', servingSize: 1, servingUnit: 'katori (150g)', calories: 70, protein: 5.5, carbs: 8.0, fats: 1.5, category: 'Dairy' },
  { name: 'Raita (Boondi)', servingSize: 1, servingUnit: 'katori (150g)', calories: 120, protein: 4.0, carbs: 12.0, fats: 6.0, category: 'Dairy' },
  { name: 'Raita (Cucumber)', servingSize: 1, servingUnit: 'katori (150g)', calories: 80, protein: 4.0, carbs: 8.0, fats: 3.5, category: 'Dairy' },
  { name: 'Lassi (Sweet)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 200, protein: 6.0, carbs: 32.0, fats: 5.0, category: 'Dairy' },
  { name: 'Lassi (Salted)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 100, protein: 5.0, carbs: 10.0, fats: 4.0, category: 'Dairy' },
  { name: 'Mango Lassi', servingSize: 1, servingUnit: 'glass (300ml)', calories: 260, protein: 6.0, carbs: 42.0, fats: 6.0, category: 'Dairy' },
  { name: 'Buttermilk (Chaas)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 40, protein: 2.0, carbs: 4.0, fats: 1.5, category: 'Dairy' },
  { name: 'Ghee', servingSize: 1, servingUnit: 'tsp (5g)', calories: 45, protein: 0.0, carbs: 0.0, fats: 5.0, category: 'Dairy' },
  { name: 'Butter', servingSize: 1, servingUnit: 'tsp (5g)', calories: 36, protein: 0.0, carbs: 0.0, fats: 4.0, category: 'Dairy' },
  { name: 'Cheese Slice', servingSize: 1, servingUnit: 'slice (20g)', calories: 60, protein: 3.5, carbs: 0.5, fats: 5.0, category: 'Dairy' },
  { name: 'Paneer Tikka', servingSize: 6, servingUnit: 'pieces (120g)', calories: 240, protein: 16.0, carbs: 4.0, fats: 18.0, category: 'Dairy' },
  { name: 'Khoya (Mawa)', servingSize: 50, servingUnit: 'grams', calories: 200, protein: 7.0, carbs: 10.0, fats: 15.0, category: 'Dairy' },
  { name: 'Soy Milk (Unsweetened)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 80, protein: 7.0, carbs: 4.0, fats: 4.0, category: 'Dairy' },
  { name: 'Almond Milk (Unsweetened)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 40, protein: 1.5, carbs: 2.0, fats: 3.0, category: 'Dairy' },
  { name: 'Paneer (Low Fat)', servingSize: 100, servingUnit: 'grams', calories: 180, protein: 20.0, carbs: 2.0, fats: 10.0, category: 'Dairy' },
  { name: 'Tofu (Firm)', servingSize: 100, servingUnit: 'grams', calories: 144, protein: 17.0, carbs: 3.0, fats: 8.0, category: 'Dairy' },
  { name: 'Curd (Buffalo Milk)', servingSize: 1, servingUnit: 'katori (150g)', calories: 150, protein: 6.0, carbs: 8.0, fats: 10.0, category: 'Dairy' },
  { name: 'Shrikhand (Mango/Amrakhand)', servingSize: 1, servingUnit: 'katori (100g)', calories: 220, protein: 4.5, carbs: 34.0, fats: 7.0, category: 'Dairy' },
  { name: 'Mishti Doi', servingSize: 1, servingUnit: 'cup (100g)', calories: 160, protein: 4.0, carbs: 24.0, fats: 5.0, category: 'Dairy' },
  { name: 'Rabri (Low Sugar)', servingSize: 1, servingUnit: 'katori (100g)', calories: 180, protein: 6.0, carbs: 20.0, fats: 8.0, category: 'Dairy' },
  { name: 'Masala Buttermilk', servingSize: 1, servingUnit: 'glass (250ml)', calories: 45, protein: 2.2, carbs: 4.5, fats: 1.8, category: 'Dairy' },
  { name: 'Whey Protein (Isolate)', servingSize: 1, servingUnit: 'scoop (30g)', calories: 110, protein: 25.0, carbs: 1.0, fats: 0.5, category: 'Dairy' },

  // ═══════════════════════════════════════════════
  // FRUITS
  // ═══════════════════════════════════════════════
  { name: 'Banana', servingSize: 1, servingUnit: 'medium (118g)', calories: 105, protein: 1.3, carbs: 27.0, fats: 0.4, category: 'Fruit' },
  { name: 'Apple', servingSize: 1, servingUnit: 'medium (182g)', calories: 95, protein: 0.5, carbs: 25.0, fats: 0.3, category: 'Fruit' },
  { name: 'Mango (Alphonso)', servingSize: 1, servingUnit: 'medium (200g)', calories: 150, protein: 1.5, carbs: 35.0, fats: 0.5, category: 'Fruit' },
  { name: 'Mango (Kesar)', servingSize: 1, servingUnit: 'medium (180g)', calories: 130, protein: 1.2, carbs: 32.0, fats: 0.4, category: 'Fruit' },
  { name: 'Papaya', servingSize: 1, servingUnit: 'cup diced (140g)', calories: 60, protein: 0.7, carbs: 15.0, fats: 0.3, category: 'Fruit' },
  { name: 'Guava', servingSize: 1, servingUnit: 'medium (100g)', calories: 68, protein: 2.5, carbs: 14.0, fats: 1.0, category: 'Fruit' },
  { name: 'Orange', servingSize: 1, servingUnit: 'medium (130g)', calories: 62, protein: 1.2, carbs: 15.0, fats: 0.2, category: 'Fruit' },
  { name: 'Sweet Lime (Mosambi)', servingSize: 1, servingUnit: 'medium (120g)', calories: 50, protein: 0.8, carbs: 12.0, fats: 0.2, category: 'Fruit' },
  { name: 'Pomegranate', servingSize: 1, servingUnit: 'medium seeds (150g)', calories: 120, protein: 2.5, carbs: 28.0, fats: 1.5, category: 'Fruit' },
  { name: 'Watermelon', servingSize: 1, servingUnit: 'cup diced (152g)', calories: 46, protein: 0.9, carbs: 11.5, fats: 0.2, category: 'Fruit' },
  { name: 'Muskmelon (Kharbuja)', servingSize: 1, servingUnit: 'cup diced (150g)', calories: 50, protein: 1.0, carbs: 12.0, fats: 0.2, category: 'Fruit' },
  { name: 'Grapes (Green)', servingSize: 1, servingUnit: 'cup (150g)', calories: 104, protein: 1.1, carbs: 27.0, fats: 0.2, category: 'Fruit' },
  { name: 'Grapes (Black)', servingSize: 1, servingUnit: 'cup (150g)', calories: 100, protein: 1.0, carbs: 26.0, fats: 0.3, category: 'Fruit' },
  { name: 'Chikoo (Sapota)', servingSize: 1, servingUnit: 'medium (100g)', calories: 83, protein: 0.4, carbs: 20.0, fats: 1.1, category: 'Fruit' },
  { name: 'Pear (Nashpati)', servingSize: 1, servingUnit: 'medium (170g)', calories: 100, protein: 0.6, carbs: 27.0, fats: 0.2, category: 'Fruit' },
  { name: 'Pineapple', servingSize: 1, servingUnit: 'cup diced (165g)', calories: 82, protein: 0.9, carbs: 22.0, fats: 0.2, category: 'Fruit' },
  { name: 'Strawberry', servingSize: 1, servingUnit: 'cup (150g)', calories: 48, protein: 1.0, carbs: 12.0, fats: 0.5, category: 'Fruit' },
  { name: 'Lychee', servingSize: 10, servingUnit: 'pieces (100g)', calories: 66, protein: 0.8, carbs: 16.5, fats: 0.4, category: 'Fruit' },
  { name: 'Jackfruit (Ripe)', servingSize: 1, servingUnit: 'cup (150g)', calories: 143, protein: 2.5, carbs: 35.0, fats: 0.5, category: 'Fruit' },
  { name: 'Custard Apple (Sitaphal)', servingSize: 1, servingUnit: 'medium (150g)', calories: 140, protein: 2.0, carbs: 34.0, fats: 0.5, category: 'Fruit' },
  { name: 'Jamun (Java Plum)', servingSize: 10, servingUnit: 'pieces (50g)', calories: 30, protein: 0.4, carbs: 7.0, fats: 0.1, category: 'Fruit' },
  { name: 'Amla (Indian Gooseberry)', servingSize: 2, servingUnit: 'pieces (40g)', calories: 18, protein: 0.3, carbs: 4.0, fats: 0.1, category: 'Fruit' },
  { name: 'Coconut (Fresh)', servingSize: 50, servingUnit: 'grams', calories: 175, protein: 1.7, carbs: 7.5, fats: 17.0, category: 'Fruit' },
  { name: 'Dates (Khajoor)', servingSize: 3, servingUnit: 'pieces (25g)', calories: 70, protein: 0.5, carbs: 18.0, fats: 0.1, category: 'Fruit' },
  { name: 'Fig (Anjeer) Fresh', servingSize: 2, servingUnit: 'pieces (80g)', calories: 60, protein: 0.6, carbs: 15.0, fats: 0.2, category: 'Fruit' },
  { name: 'Kiwi', servingSize: 1, servingUnit: 'piece (70g)', calories: 42, protein: 0.8, carbs: 10.0, fats: 0.4, category: 'Fruit' },
  { name: 'Plum (Aloo Bukhara)', servingSize: 2, servingUnit: 'pieces (130g)', calories: 60, protein: 0.9, carbs: 14.0, fats: 0.4, category: 'Fruit' },
  { name: 'Peach (Aadu)', servingSize: 1, servingUnit: 'medium (150g)', calories: 58, protein: 1.4, carbs: 14.0, fats: 0.4, category: 'Fruit' },
  { name: 'Dragon Fruit', servingSize: 1, servingUnit: 'medium (200g)', calories: 100, protein: 2.0, carbs: 22.0, fats: 0.5, category: 'Fruit' },
  { name: 'Avocado', servingSize: 0.5, servingUnit: 'piece (70g)', calories: 115, protein: 1.4, carbs: 6.0, fats: 10.5, category: 'Fruit' },
  { name: 'Guava (Pink)', servingSize: 1, servingUnit: 'medium (100g)', calories: 65, protein: 2.4, carbs: 13.5, fats: 0.9, category: 'Fruit' },
  { name: 'Wood Apple (Bael)', servingSize: 1, servingUnit: 'medium (150g)', calories: 130, protein: 1.8, carbs: 31.0, fats: 0.3, category: 'Fruit' },
  { name: 'Star Fruit (Carambola)', servingSize: 1, servingUnit: 'medium (90g)', calories: 28, protein: 0.9, carbs: 6.0, fats: 0.3, category: 'Fruit' },
  { name: 'Mulberry (Shahtoot)', servingSize: 1, servingUnit: 'cup (140g)', calories: 60, protein: 2.0, carbs: 14.0, fats: 0.5, category: 'Fruit' },
  { name: 'Cape Gooseberry (Rasbhari)', servingSize: 10, servingUnit: 'pieces (50g)', calories: 26, protein: 0.9, carbs: 5.6, fats: 0.3, category: 'Fruit' },
  { name: 'Phalsa', servingSize: 50, servingUnit: 'grams', calories: 36, protein: 0.8, carbs: 8.5, fats: 0.2, category: 'Fruit' },

  // ═══════════════════════════════════════════════
  // VEGETABLES (RAW/COOKED)
  // ═══════════════════════════════════════════════
  { name: 'Potato (Boiled)', servingSize: 1, servingUnit: 'medium (150g)', calories: 130, protein: 3.0, carbs: 30.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Sweet Potato (Boiled)', servingSize: 1, servingUnit: 'medium (130g)', calories: 115, protein: 2.0, carbs: 27.0, fats: 0.1, category: 'Vegetable' },
  { name: 'Onion (Raw)', servingSize: 1, servingUnit: 'medium (110g)', calories: 44, protein: 1.2, carbs: 10.0, fats: 0.1, category: 'Vegetable' },
  { name: 'Tomato', servingSize: 1, servingUnit: 'medium (125g)', calories: 22, protein: 1.1, carbs: 4.8, fats: 0.2, category: 'Vegetable' },
  { name: 'Spinach (Palak) Cooked', servingSize: 1, servingUnit: 'cup (180g)', calories: 41, protein: 5.0, carbs: 7.0, fats: 0.5, category: 'Vegetable' },
  { name: 'Cauliflower (Gobi)', servingSize: 1, servingUnit: 'cup (100g)', calories: 25, protein: 2.0, carbs: 5.0, fats: 0.3, category: 'Vegetable' },
  { name: 'Cabbage', servingSize: 1, servingUnit: 'cup shredded (90g)', calories: 22, protein: 1.1, carbs: 5.0, fats: 0.1, category: 'Vegetable' },
  { name: 'Broccoli', servingSize: 1, servingUnit: 'cup (90g)', calories: 31, protein: 2.5, carbs: 6.0, fats: 0.3, category: 'Vegetable' },
  { name: 'Carrot', servingSize: 1, servingUnit: 'medium (60g)', calories: 25, protein: 0.6, carbs: 6.0, fats: 0.1, category: 'Vegetable' },
  { name: 'Cucumber', servingSize: 1, servingUnit: 'medium (200g)', calories: 30, protein: 1.3, carbs: 7.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Green Peas', servingSize: 1, servingUnit: 'cup (145g)', calories: 118, protein: 8.0, carbs: 21.0, fats: 0.6, category: 'Vegetable' },
  { name: 'Corn (Sweet)', servingSize: 1, servingUnit: 'cob (100g)', calories: 86, protein: 3.0, carbs: 19.0, fats: 1.2, category: 'Vegetable' },
  { name: 'Beetroot', servingSize: 1, servingUnit: 'medium (80g)', calories: 35, protein: 1.3, carbs: 8.0, fats: 0.1, category: 'Vegetable' },
  { name: 'Radish (Mooli)', servingSize: 1, servingUnit: 'medium (100g)', calories: 16, protein: 0.7, carbs: 3.5, fats: 0.1, category: 'Vegetable' },
  { name: 'Bottle Gourd (Lauki)', servingSize: 1, servingUnit: 'cup diced (120g)', calories: 17, protein: 0.7, carbs: 4.0, fats: 0.0, category: 'Vegetable' },
  { name: 'Ridge Gourd (Tori)', servingSize: 1, servingUnit: 'cup (120g)', calories: 20, protein: 1.2, carbs: 4.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Bitter Gourd (Karela)', servingSize: 1, servingUnit: 'cup sliced (95g)', calories: 17, protein: 1.0, carbs: 3.5, fats: 0.2, category: 'Vegetable' },
  { name: 'Okra (Bhindi)', servingSize: 1, servingUnit: 'cup (100g)', calories: 33, protein: 1.9, carbs: 7.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Brinjal (Baingan)', servingSize: 1, servingUnit: 'cup diced (80g)', calories: 20, protein: 0.8, carbs: 5.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Capsicum (Bell Pepper)', servingSize: 1, servingUnit: 'medium (120g)', calories: 25, protein: 1.0, carbs: 6.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Green Beans (French Beans)', servingSize: 1, servingUnit: 'cup (100g)', calories: 31, protein: 1.8, carbs: 7.0, fats: 0.1, category: 'Vegetable' },
  { name: 'Drumstick (Moringa)', servingSize: 2, servingUnit: 'sticks (100g)', calories: 37, protein: 2.1, carbs: 8.5, fats: 0.2, category: 'Vegetable' },
  { name: 'Mushroom (Button)', servingSize: 1, servingUnit: 'cup (70g)', calories: 15, protein: 2.2, carbs: 2.3, fats: 0.2, category: 'Vegetable' },
  { name: 'Lettuce', servingSize: 1, servingUnit: 'cup shredded (55g)', calories: 8, protein: 0.5, carbs: 1.5, fats: 0.1, category: 'Vegetable' },
  { name: 'Green Chilli', servingSize: 1, servingUnit: 'piece (5g)', calories: 2, protein: 0.1, carbs: 0.4, fats: 0.0, category: 'Vegetable' },
  { name: 'Ginger (Fresh)', servingSize: 1, servingUnit: 'tbsp grated (6g)', calories: 5, protein: 0.1, carbs: 1.1, fats: 0.0, category: 'Vegetable' },
  { name: 'Garlic', servingSize: 3, servingUnit: 'cloves (9g)', calories: 13, protein: 0.6, carbs: 3.0, fats: 0.0, category: 'Vegetable' },
  { name: 'Parwal (Pointed Gourd) raw', servingSize: 100, servingUnit: 'grams', calories: 20, protein: 1.4, carbs: 4.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Tinda (Apple Gourd) raw', servingSize: 100, servingUnit: 'grams', calories: 18, protein: 1.0, carbs: 3.5, fats: 0.2, category: 'Vegetable' },
  { name: 'Lauki (Bottle Gourd) raw', servingSize: 100, servingUnit: 'grams', calories: 15, protein: 0.6, carbs: 3.3, fats: 0.1, category: 'Vegetable' },
  { name: 'Ridge Gourd raw', servingSize: 100, servingUnit: 'grams', calories: 17, protein: 0.8, carbs: 3.5, fats: 0.1, category: 'Vegetable' },
  { name: 'Bitter Gourd raw', servingSize: 100, servingUnit: 'grams', calories: 25, protein: 1.5, carbs: 5.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Colocasia root (Arbi) boiled', servingSize: 100, servingUnit: 'grams', calories: 110, protein: 1.5, carbs: 26.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Elephant Foot Yam (Suran) boiled', servingSize: 100, servingUnit: 'grams', calories: 120, protein: 1.8, carbs: 28.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Amaranth leaves (Chaulai) raw', servingSize: 100, servingUnit: 'grams', calories: 23, protein: 2.5, carbs: 4.0, fats: 0.3, category: 'Vegetable' },
  { name: 'Bathua leaves raw', servingSize: 100, servingUnit: 'grams', calories: 30, protein: 4.0, carbs: 4.5, fats: 0.5, category: 'Vegetable' },
  { name: 'Fenugreek leaves (Methi) raw', servingSize: 100, servingUnit: 'grams', calories: 49, protein: 4.4, carbs: 6.0, fats: 0.9, category: 'Vegetable' },

  // ═══════════════════════════════════════════════
  // BEVERAGES
  // ═══════════════════════════════════════════════
  { name: 'Masala Chai', servingSize: 1, servingUnit: 'cup (150ml)', calories: 60, protein: 2.0, carbs: 8.0, fats: 2.0, category: 'Beverage' },
  { name: 'Chai (No Sugar)', servingSize: 1, servingUnit: 'cup (150ml)', calories: 25, protein: 2.0, carbs: 2.0, fats: 1.0, category: 'Beverage' },
  { name: 'Black Tea', servingSize: 1, servingUnit: 'cup (200ml)', calories: 2, protein: 0.0, carbs: 0.5, fats: 0.0, category: 'Beverage' },
  { name: 'Green Tea', servingSize: 1, servingUnit: 'cup (200ml)', calories: 2, protein: 0.0, carbs: 0.5, fats: 0.0, category: 'Beverage' },
  { name: 'Coffee (with Milk & Sugar)', servingSize: 1, servingUnit: 'cup (150ml)', calories: 70, protein: 2.0, carbs: 10.0, fats: 2.0, category: 'Beverage' },
  { name: 'Filter Coffee (South Indian)', servingSize: 1, servingUnit: 'cup (150ml)', calories: 80, protein: 2.0, carbs: 10.0, fats: 3.0, category: 'Beverage' },
  { name: 'Black Coffee', servingSize: 1, servingUnit: 'cup (200ml)', calories: 5, protein: 0.3, carbs: 0.0, fats: 0.0, category: 'Beverage' },
  { name: 'Nimbu Pani (Lemon Water)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 40, protein: 0.2, carbs: 10.0, fats: 0.0, category: 'Beverage' },
  { name: 'Coconut Water', servingSize: 1, servingUnit: 'glass (250ml)', calories: 46, protein: 1.7, carbs: 9.0, fats: 0.5, category: 'Beverage' },
  { name: 'Sugarcane Juice', servingSize: 1, servingUnit: 'glass (250ml)', calories: 180, protein: 0.5, carbs: 45.0, fats: 0.0, category: 'Beverage' },
  { name: 'Mango Shake', servingSize: 1, servingUnit: 'glass (300ml)', calories: 260, protein: 5.0, carbs: 45.0, fats: 6.0, category: 'Beverage' },
  { name: 'Banana Shake', servingSize: 1, servingUnit: 'glass (300ml)', calories: 220, protein: 6.0, carbs: 38.0, fats: 5.0, category: 'Beverage' },
  { name: 'Badam Milk', servingSize: 1, servingUnit: 'glass (250ml)', calories: 200, protein: 8.0, carbs: 22.0, fats: 9.0, category: 'Beverage' },
  { name: 'Thandai', servingSize: 1, servingUnit: 'glass (250ml)', calories: 250, protein: 6.0, carbs: 30.0, fats: 12.0, category: 'Beverage' },
  { name: 'Aam Panna', servingSize: 1, servingUnit: 'glass (250ml)', calories: 80, protein: 0.5, carbs: 20.0, fats: 0.2, category: 'Beverage' },
  { name: 'Jal Jeera', servingSize: 1, servingUnit: 'glass (250ml)', calories: 30, protein: 0.5, carbs: 7.0, fats: 0.1, category: 'Beverage' },
  { name: 'Rooh Afza Sharbat', servingSize: 1, servingUnit: 'glass (250ml)', calories: 130, protein: 0.0, carbs: 32.0, fats: 0.0, category: 'Beverage' },
  { name: 'Cola (Soft Drink)', servingSize: 1, servingUnit: 'can (330ml)', calories: 140, protein: 0.0, carbs: 35.0, fats: 0.0, category: 'Beverage' },
  { name: 'Fresh Orange Juice', servingSize: 1, servingUnit: 'glass (250ml)', calories: 112, protein: 1.7, carbs: 26.0, fats: 0.5, category: 'Beverage' },
  { name: 'Mixed Fruit Juice', servingSize: 1, servingUnit: 'glass (250ml)', calories: 130, protein: 1.0, carbs: 32.0, fats: 0.3, category: 'Beverage' },
  { name: 'Protein Shake (Whey)', servingSize: 1, servingUnit: 'scoop (30g) + water', calories: 120, protein: 24.0, carbs: 3.0, fats: 1.5, category: 'Beverage' },
  { name: 'Rose Milk', servingSize: 1, servingUnit: 'glass (250ml)', calories: 180, protein: 7.0, carbs: 28.0, fats: 4.5, category: 'Beverage' },
  { name: 'Lemon Tea', servingSize: 1, servingUnit: 'cup (150ml)', calories: 30, protein: 0.1, carbs: 7.5, fats: 0.0, category: 'Beverage' },
  { name: 'Ginger Tea', servingSize: 1, servingUnit: 'cup (150ml)', calories: 45, protein: 1.2, carbs: 6.5, fats: 1.5, category: 'Beverage' },
  { name: 'Kokum Sharbat', servingSize: 1, servingUnit: 'glass (250ml)', calories: 90, protein: 0.2, carbs: 22.0, fats: 0.1, category: 'Beverage' },
  { name: 'Kashaya', servingSize: 1, servingUnit: 'cup (150ml)', calories: 60, protein: 1.5, carbs: 10.0, fats: 1.5, category: 'Beverage' },
  { name: 'Nannari Syrup Sharbat', servingSize: 1, servingUnit: 'glass (250ml)', calories: 100, protein: 0.0, carbs: 25.0, fats: 0.0, category: 'Beverage' },
  { name: 'Solkadhi', servingSize: 1, servingUnit: 'glass (150ml)', calories: 75, protein: 1.0, carbs: 3.0, fats: 6.5, category: 'Beverage' },
  { name: 'Sattu Drink', servingSize: 1, servingUnit: 'glass (250ml)', calories: 120, protein: 6.0, carbs: 20.0, fats: 2.0, category: 'Beverage' },
  { name: 'Masala Chai (Stevia)', servingSize: 1, servingUnit: 'cup (150ml)', calories: 35, protein: 2.0, carbs: 4.0, fats: 1.5, category: 'Beverage' },
  { name: 'Filter Coffee (Stevia)', servingSize: 1, servingUnit: 'cup (150ml)', calories: 40, protein: 2.0, carbs: 4.0, fats: 2.0, category: 'Beverage' },

  // ═══════════════════════════════════════════════
  // SWEETS & DESSERTS
  // ═══════════════════════════════════════════════
  { name: 'Gulab Jamun', servingSize: 2, servingUnit: 'pieces (60g)', calories: 300, protein: 3.0, carbs: 40.0, fats: 14.0, category: 'Sweets' },
  { name: 'Rasgulla', servingSize: 2, servingUnit: 'pieces (80g)', calories: 180, protein: 4.0, carbs: 35.0, fats: 3.0, category: 'Sweets' },
  { name: 'Rasmalai', servingSize: 2, servingUnit: 'pieces (100g)', calories: 250, protein: 6.0, carbs: 35.0, fats: 10.0, category: 'Sweets' },
  { name: 'Jalebi', servingSize: 2, servingUnit: 'pieces (60g)', calories: 250, protein: 2.0, carbs: 38.0, fats: 10.0, category: 'Sweets' },
  { name: 'Barfi (Kaju)', servingSize: 1, servingUnit: 'piece (30g)', calories: 130, protein: 3.0, carbs: 14.0, fats: 7.0, category: 'Sweets' },
  { name: 'Barfi (Besan)', servingSize: 1, servingUnit: 'piece (30g)', calories: 120, protein: 2.5, carbs: 15.0, fats: 6.0, category: 'Sweets' },
  { name: 'Ladoo (Besan)', servingSize: 1, servingUnit: 'piece (40g)', calories: 180, protein: 3.0, carbs: 20.0, fats: 10.0, category: 'Sweets' },
  { name: 'Ladoo (Motichoor)', servingSize: 1, servingUnit: 'piece (35g)', calories: 160, protein: 2.0, carbs: 22.0, fats: 7.0, category: 'Sweets' },
  { name: 'Ladoo (Boondi)', servingSize: 1, servingUnit: 'piece (35g)', calories: 155, protein: 2.0, carbs: 21.0, fats: 7.0, category: 'Sweets' },
  { name: 'Peda', servingSize: 1, servingUnit: 'piece (25g)', calories: 100, protein: 2.5, carbs: 14.0, fats: 4.0, category: 'Sweets' },
  { name: 'Kheer (Rice)', servingSize: 1, servingUnit: 'katori (150g)', calories: 200, protein: 5.0, carbs: 30.0, fats: 7.0, category: 'Sweets' },
  { name: 'Sewai Kheer', servingSize: 1, servingUnit: 'katori (150g)', calories: 210, protein: 5.0, carbs: 32.0, fats: 7.0, category: 'Sweets' },
  { name: 'Phirni', servingSize: 1, servingUnit: 'katori (150g)', calories: 190, protein: 4.5, carbs: 28.0, fats: 7.0, category: 'Sweets' },
  { name: 'Halwa (Suji)', servingSize: 1, servingUnit: 'katori (100g)', calories: 250, protein: 3.0, carbs: 32.0, fats: 12.0, category: 'Sweets' },
  { name: 'Halwa (Gajar)', servingSize: 1, servingUnit: 'katori (100g)', calories: 220, protein: 3.0, carbs: 28.0, fats: 11.0, category: 'Sweets' },
  { name: 'Halwa (Moong Dal)', servingSize: 1, servingUnit: 'katori (100g)', calories: 280, protein: 5.0, carbs: 30.0, fats: 15.0, category: 'Sweets' },
  { name: 'Rabri', servingSize: 1, servingUnit: 'katori (100g)', calories: 220, protein: 5.0, carbs: 22.0, fats: 12.0, category: 'Sweets' },
  { name: 'Kulfi', servingSize: 1, servingUnit: 'stick (80g)', calories: 160, protein: 3.0, carbs: 20.0, fats: 8.0, category: 'Sweets' },
  { name: 'Sandesh', servingSize: 2, servingUnit: 'pieces (50g)', calories: 130, protein: 4.0, carbs: 18.0, fats: 5.0, category: 'Sweets' },
  { name: 'Mysore Pak', servingSize: 1, servingUnit: 'piece (40g)', calories: 200, protein: 3.0, carbs: 20.0, fats: 12.0, category: 'Sweets' },
  { name: 'Imarti', servingSize: 1, servingUnit: 'piece (40g)', calories: 180, protein: 2.0, carbs: 28.0, fats: 7.0, category: 'Sweets' },
  { name: 'Malpua', servingSize: 1, servingUnit: 'piece (60g)', calories: 200, protein: 3.0, carbs: 26.0, fats: 10.0, category: 'Sweets' },
  { name: 'Payasam (Vermicelli)', servingSize: 1, servingUnit: 'katori (150g)', calories: 220, protein: 4.0, carbs: 34.0, fats: 8.0, category: 'Sweets' },
  { name: 'Shrikhand', servingSize: 1, servingUnit: 'katori (100g)', calories: 200, protein: 5.0, carbs: 28.0, fats: 8.0, category: 'Sweets' },
  { name: 'Ras Malai', servingSize: 2, servingUnit: 'pieces (100g)', calories: 250, protein: 6.0, carbs: 35.0, fats: 10.0, category: 'Sweets' },
  { name: 'Motichoor Ladoo', servingSize: 1, servingUnit: 'piece (40g)', calories: 170, protein: 2.0, carbs: 24.0, fats: 8.0, category: 'Sweets' },
  { name: 'Pista Barfi', servingSize: 1, servingUnit: 'piece (30g)', calories: 135, protein: 3.0, carbs: 15.0, fats: 7.0, category: 'Sweets' },
  { name: 'Besan Ladoo', servingSize: 1, servingUnit: 'piece (40g)', calories: 185, protein: 3.5, carbs: 22.0, fats: 9.0, category: 'Sweets' },
  { name: 'Sohan Papdi', servingSize: 1, servingUnit: 'piece (35g)', calories: 160, protein: 2.0, carbs: 20.0, fats: 8.0, category: 'Sweets' },
  { name: 'Peda (Mathura)', servingSize: 1, servingUnit: 'piece (25g)', calories: 105, protein: 2.5, carbs: 13.0, fats: 4.5, category: 'Sweets' },
  { name: 'Ghevar', servingSize: 1, servingUnit: 'piece (80g)', calories: 320, protein: 4.0, carbs: 45.0, fats: 14.0, category: 'Sweets' },
  { name: 'Chhena Poda', servingSize: 1, servingUnit: 'slice (80g)', calories: 160, protein: 6.0, carbs: 24.0, fats: 5.0, category: 'Sweets' },
  { name: 'Adhirasam', servingSize: 1, servingUnit: 'piece (50g)', calories: 210, protein: 3.0, carbs: 32.0, fats: 8.0, category: 'Sweets' },
  { name: 'Unniyappam', servingSize: 3, servingUnit: 'pieces (75g)', calories: 230, protein: 3.5, carbs: 35.0, fats: 8.5, category: 'Sweets' },
  { name: 'Karanji (Gujiya)', servingSize: 1, servingUnit: 'piece (50g)', calories: 190, protein: 3.0, carbs: 26.0, fats: 8.5, category: 'Sweets' },

  // ═══════════════════════════════════════════════
  // DRY FRUITS & NUTS
  // ═══════════════════════════════════════════════
  { name: 'Almonds (Badam)', servingSize: 10, servingUnit: 'pieces (14g)', calories: 80, protein: 3.0, carbs: 3.0, fats: 7.0, category: 'Dry Fruits' },
  { name: 'Cashews (Kaju)', servingSize: 10, servingUnit: 'pieces (15g)', calories: 85, protein: 2.5, carbs: 4.5, fats: 6.5, category: 'Dry Fruits' },
  { name: 'Walnuts (Akhrot)', servingSize: 5, servingUnit: 'halves (14g)', calories: 90, protein: 2.0, carbs: 2.0, fats: 9.0, category: 'Dry Fruits' },
  { name: 'Pistachios (Pista)', servingSize: 15, servingUnit: 'pieces (15g)', calories: 85, protein: 3.0, carbs: 4.0, fats: 7.0, category: 'Dry Fruits' },
  { name: 'Raisins (Kishmish)', servingSize: 20, servingUnit: 'pieces (15g)', calories: 45, protein: 0.5, carbs: 12.0, fats: 0.0, category: 'Dry Fruits' },
  { name: 'Dried Figs (Anjeer)', servingSize: 2, servingUnit: 'pieces (20g)', calories: 50, protein: 0.6, carbs: 13.0, fats: 0.2, category: 'Dry Fruits' },
  { name: 'Dried Dates (Chhuhara)', servingSize: 3, servingUnit: 'pieces (20g)', calories: 55, protein: 0.5, carbs: 14.0, fats: 0.1, category: 'Dry Fruits' },
  { name: 'Peanuts (Mungfali)', servingSize: 30, servingUnit: 'grams', calories: 170, protein: 7.0, carbs: 5.0, fats: 14.0, category: 'Dry Fruits' },
  { name: 'Flax Seeds (Alsi)', servingSize: 1, servingUnit: 'tbsp (10g)', calories: 55, protein: 2.0, carbs: 3.0, fats: 4.0, category: 'Dry Fruits' },
  { name: 'Chia Seeds', servingSize: 1, servingUnit: 'tbsp (12g)', calories: 60, protein: 2.0, carbs: 5.0, fats: 4.0, category: 'Dry Fruits' },
  { name: 'Sunflower Seeds', servingSize: 1, servingUnit: 'tbsp (10g)', calories: 58, protein: 2.0, carbs: 2.0, fats: 5.0, category: 'Dry Fruits' },
  { name: 'Pumpkin Seeds', servingSize: 1, servingUnit: 'tbsp (10g)', calories: 55, protein: 2.5, carbs: 1.5, fats: 5.0, category: 'Dry Fruits' },
  { name: 'Sesame Seeds (Til)', servingSize: 1, servingUnit: 'tbsp (9g)', calories: 52, protein: 1.6, carbs: 2.0, fats: 4.5, category: 'Dry Fruits' },
  { name: 'Dried Apricot (Khubani)', servingSize: 3, servingUnit: 'pieces (20g)', calories: 50, protein: 0.7, carbs: 12.0, fats: 0.1, category: 'Dry Fruits' },
  { name: 'Coconut (Dried/Copra)', servingSize: 20, servingUnit: 'grams', calories: 130, protein: 1.3, carbs: 5.0, fats: 13.0, category: 'Dry Fruits' },

  // ═══════════════════════════════════════════════
  // CONDIMENTS, CHUTNEYS & EXTRAS
  // ═══════════════════════════════════════════════
  { name: 'Mango Pickle (Achaar)', servingSize: 1, servingUnit: 'tbsp (15g)', calories: 30, protein: 0.2, carbs: 2.0, fats: 2.5, category: 'Condiment' },
  { name: 'Lemon Pickle', servingSize: 1, servingUnit: 'tbsp (15g)', calories: 25, protein: 0.2, carbs: 2.0, fats: 2.0, category: 'Condiment' },
  { name: 'Mixed Pickle', servingSize: 1, servingUnit: 'tbsp (15g)', calories: 30, protein: 0.3, carbs: 2.0, fats: 2.5, category: 'Condiment' },
  { name: 'Coconut Chutney', servingSize: 2, servingUnit: 'tbsp (30g)', calories: 50, protein: 1.0, carbs: 3.0, fats: 4.0, category: 'Condiment' },
  { name: 'Mint Chutney (Pudina)', servingSize: 2, servingUnit: 'tbsp (30g)', calories: 15, protein: 0.5, carbs: 2.0, fats: 0.5, category: 'Condiment' },
  { name: 'Tamarind Chutney', servingSize: 2, servingUnit: 'tbsp (30g)', calories: 40, protein: 0.2, carbs: 10.0, fats: 0.1, category: 'Condiment' },
  { name: 'Tomato Ketchup', servingSize: 1, servingUnit: 'tbsp (15g)', calories: 20, protein: 0.2, carbs: 5.0, fats: 0.0, category: 'Condiment' },
  { name: 'Green Chutney (Coriander)', servingSize: 2, servingUnit: 'tbsp (30g)', calories: 10, protein: 0.5, carbs: 1.5, fats: 0.3, category: 'Condiment' },
  { name: 'Peanut Chutney', servingSize: 2, servingUnit: 'tbsp (30g)', calories: 70, protein: 3.0, carbs: 3.0, fats: 5.0, category: 'Condiment' },
  { name: 'Sugar', servingSize: 1, servingUnit: 'tsp (4g)', calories: 16, protein: 0.0, carbs: 4.0, fats: 0.0, category: 'Condiment' },
  { name: 'Honey', servingSize: 1, servingUnit: 'tsp (7g)', calories: 21, protein: 0.0, carbs: 5.7, fats: 0.0, category: 'Condiment' },
  { name: 'Jaggery (Gur)', servingSize: 1, servingUnit: 'tbsp (20g)', calories: 76, protein: 0.2, carbs: 19.0, fats: 0.0, category: 'Condiment' },
  { name: 'Cooking Oil', servingSize: 1, servingUnit: 'tsp (5ml)', calories: 45, protein: 0.0, carbs: 0.0, fats: 5.0, category: 'Condiment' },
  { name: 'Mustard Oil', servingSize: 1, servingUnit: 'tsp (5ml)', calories: 45, protein: 0.0, carbs: 0.0, fats: 5.0, category: 'Condiment' },
  { name: 'Olive Oil', servingSize: 1, servingUnit: 'tsp (5ml)', calories: 40, protein: 0.0, carbs: 0.0, fats: 4.5, category: 'Condiment' },

  // ═══════════════════════════════════════════════
  // STREET FOOD & COMPLETE MEALS
  // ═══════════════════════════════════════════════
  { name: 'Dahi Bhalla', servingSize: 2, servingUnit: 'pieces (120g)', calories: 200, protein: 5.0, carbs: 28.0, fats: 8.0, category: 'Street Food' },
  { name: 'Aloo Chaat', servingSize: 1, servingUnit: 'plate (150g)', calories: 220, protein: 4.0, carbs: 32.0, fats: 9.0, category: 'Street Food' },
  { name: 'Papdi Chaat', servingSize: 1, servingUnit: 'plate (150g)', calories: 250, protein: 5.0, carbs: 30.0, fats: 12.0, category: 'Street Food' },
  { name: 'Frankie (Veg)', servingSize: 1, servingUnit: 'roll (200g)', calories: 320, protein: 8.0, carbs: 40.0, fats: 14.0, category: 'Street Food' },
  { name: 'Frankie (Chicken)', servingSize: 1, servingUnit: 'roll (220g)', calories: 380, protein: 16.0, carbs: 38.0, fats: 18.0, category: 'Street Food' },
  { name: 'Egg Roll', servingSize: 1, servingUnit: 'roll (200g)', calories: 340, protein: 14.0, carbs: 36.0, fats: 15.0, category: 'Street Food' },
  { name: 'Paneer Roll', servingSize: 1, servingUnit: 'roll (200g)', calories: 360, protein: 14.0, carbs: 36.0, fats: 18.0, category: 'Street Food' },
  { name: 'Bread Pakora', servingSize: 1, servingUnit: 'piece (80g)', calories: 200, protein: 4.0, carbs: 22.0, fats: 11.0, category: 'Street Food' },
  { name: 'Kathi Roll (Chicken)', servingSize: 1, servingUnit: 'roll (200g)', calories: 350, protein: 18.0, carbs: 35.0, fats: 15.0, category: 'Street Food' },
  { name: 'Tawa Pulao', servingSize: 1, servingUnit: 'plate (250g)', calories: 350, protein: 7.0, carbs: 52.0, fats: 12.0, category: 'Street Food' },
  { name: 'Fried Rice (Veg)', servingSize: 1, servingUnit: 'plate (250g)', calories: 320, protein: 6.0, carbs: 48.0, fats: 12.0, category: 'Street Food' },
  { name: 'Hakka Noodles (Veg)', servingSize: 1, servingUnit: 'plate (250g)', calories: 340, protein: 6.0, carbs: 50.0, fats: 13.0, category: 'Street Food' },
  { name: 'Manchurian (Veg)', servingSize: 1, servingUnit: 'plate (200g)', calories: 280, protein: 5.0, carbs: 30.0, fats: 15.0, category: 'Street Food' },
  { name: 'Chilli Paneer', servingSize: 1, servingUnit: 'plate (200g)', calories: 320, protein: 14.0, carbs: 16.0, fats: 22.0, category: 'Street Food' },
  { name: 'Paneer Fried Rice', servingSize: 1, servingUnit: 'plate (250g)', calories: 380, protein: 12.0, carbs: 48.0, fats: 16.0, category: 'Street Food' },
  { name: 'Chicken Fried Rice', servingSize: 1, servingUnit: 'plate (250g)', calories: 400, protein: 16.0, carbs: 48.0, fats: 16.0, category: 'Street Food' },
  { name: 'Egg Fried Rice', servingSize: 1, servingUnit: 'plate (250g)', calories: 360, protein: 12.0, carbs: 48.0, fats: 14.0, category: 'Street Food' },
  { name: 'Maggi Noodles', servingSize: 1, servingUnit: 'pack (70g)', calories: 310, protein: 7.0, carbs: 42.0, fats: 13.0, category: 'Street Food' },
  { name: 'Bhelpuri', servingSize: 1, servingUnit: 'plate (150g)', calories: 180, protein: 4.0, carbs: 30.0, fats: 5.0, category: 'Street Food' },
  { name: 'Chaat (Mixed)', servingSize: 1, servingUnit: 'plate (150g)', calories: 200, protein: 4.0, carbs: 30.0, fats: 7.0, category: 'Street Food' },
  { name: 'Pizza Slice (Cheese)', servingSize: 1, servingUnit: 'slice (100g)', calories: 260, protein: 10.0, carbs: 30.0, fats: 10.0, category: 'Street Food' },
  { name: 'Veg Burger', servingSize: 1, servingUnit: 'piece (200g)', calories: 350, protein: 10.0, carbs: 42.0, fats: 14.0, category: 'Street Food' },
  { name: 'Chicken Burger', servingSize: 1, servingUnit: 'piece (220g)', calories: 420, protein: 18.0, carbs: 40.0, fats: 20.0, category: 'Street Food' },
  { name: 'French Fries', servingSize: 1, servingUnit: 'medium (100g)', calories: 312, protein: 3.4, carbs: 41.0, fats: 15.0, category: 'Street Food' },
  { name: 'Sandwich (Veg Grilled)', servingSize: 1, servingUnit: 'piece (150g)', calories: 280, protein: 8.0, carbs: 32.0, fats: 13.0, category: 'Street Food' },

  // ═══════════════════════════════════════════════
  // ADDITIONAL 100+ ITEMS TO HIT 500+ TOTAL
  // ═══════════════════════════════════════════════
  { name: 'Multigrain Chapati', servingSize: 1, servingUnit: 'piece (40g)', calories: 95, protein: 3.8, carbs: 16.0, fats: 1.8, category: 'Bread' },
  { name: 'Oats Roti', servingSize: 1, servingUnit: 'piece (45g)', calories: 110, protein: 3.5, carbs: 18.0, fats: 2.0, category: 'Bread' },
  { name: 'Barley Roti', servingSize: 1, servingUnit: 'piece (45g)', calories: 105, protein: 3.0, carbs: 20.0, fats: 1.5, category: 'Bread' },
  { name: 'Soy Roti', servingSize: 1, servingUnit: 'piece (45g)', calories: 125, protein: 6.0, carbs: 15.0, fats: 3.0, category: 'Bread' },
  { name: 'Besan Roti', servingSize: 1, servingUnit: 'piece (50g)', calories: 140, protein: 5.5, carbs: 18.0, fats: 4.0, category: 'Bread' },
  { name: 'Bran Roti', servingSize: 1, servingUnit: 'piece (45g)', calories: 90, protein: 3.2, carbs: 15.0, fats: 1.2, category: 'Bread' },
  { name: 'Singoda Poori', servingSize: 1, servingUnit: 'piece (30g)', calories: 135, protein: 1.5, carbs: 16.0, fats: 7.0, category: 'Bread' },
  { name: 'Rajgira Poori', servingSize: 1, servingUnit: 'piece (30g)', calories: 140, protein: 2.2, carbs: 15.0, fats: 8.0, category: 'Bread' },
  { name: 'Masala Puri', servingSize: 1, servingUnit: 'piece (30g)', calories: 130, protein: 2.2, carbs: 14.0, fats: 7.0, category: 'Bread' },
  { name: 'Paneer Naan', servingSize: 1, servingUnit: 'piece (120g)', calories: 340, protein: 12.0, carbs: 42.0, fats: 14.0, category: 'Bread' },
  { name: 'Chili Cheese Naan', servingSize: 1, servingUnit: 'piece (120g)', calories: 360, protein: 13.0, carbs: 40.0, fats: 16.0, category: 'Bread' },
  { name: 'Peshawari Naan', servingSize: 1, servingUnit: 'piece (120g)', calories: 380, protein: 9.0, carbs: 48.0, fats: 16.0, category: 'Bread' },
  { name: 'Keema Naan', servingSize: 1, servingUnit: 'piece (130g)', calories: 390, protein: 18.0, carbs: 40.0, fats: 18.0, category: 'Bread' },
  { name: 'Khoba Roti', servingSize: 1, servingUnit: 'piece (80g)', calories: 240, protein: 6.0, carbs: 44.0, fats: 4.0, category: 'Bread' },
  { name: 'Bhakri (Sorghum)', servingSize: 1, servingUnit: 'piece (60g)', calories: 140, protein: 3.8, carbs: 28.0, fats: 1.5, category: 'Bread' },

  { name: 'Quinoa Biryani', servingSize: 1, servingUnit: 'plate (250g)', calories: 280, protein: 10.5, carbs: 44.0, fats: 7.0, category: 'Rice & Grains' },
  { name: 'Tomato Bath', servingSize: 1, servingUnit: 'plate (200g)', calories: 230, protein: 4.8, carbs: 40.0, fats: 5.5, category: 'Rice & Grains' },
  { name: 'Vangi Bath', servingSize: 1, servingUnit: 'plate (200g)', calories: 240, protein: 4.5, carbs: 42.0, fats: 6.0, category: 'Rice & Grains' },
  { name: 'Bisi Bele Bath', servingSize: 1, servingUnit: 'plate (250g)', calories: 280, protein: 8.5, carbs: 44.0, fats: 8.0, category: 'Rice & Grains' },
  { name: 'Puliyogare', servingSize: 1, servingUnit: 'plate (200g)', calories: 255, protein: 4.0, carbs: 44.0, fats: 7.0, category: 'Rice & Grains' },
  { name: 'MTR Pulao', servingSize: 1, servingUnit: 'plate (200g)', calories: 260, protein: 5.0, carbs: 42.0, fats: 8.0, category: 'Rice & Grains' },
  { name: 'Coriander Rice', servingSize: 1, servingUnit: 'plate (200g)', calories: 225, protein: 4.2, carbs: 40.0, fats: 5.0, category: 'Rice & Grains' },
  { name: 'Garlic Fried Rice', servingSize: 1, servingUnit: 'plate (200g)', calories: 240, protein: 4.5, carbs: 42.0, fats: 6.0, category: 'Rice & Grains' },
  { name: 'Sago Pulao', servingSize: 1, servingUnit: 'plate (200g)', calories: 290, protein: 3.2, carbs: 55.0, fats: 6.0, category: 'Rice & Grains' },

  { name: 'Green Moong Dal (Whole)', servingSize: 1, servingUnit: 'katori (150g)', calories: 140, protein: 9.0, carbs: 23.0, fats: 1.2, category: 'Dal & Lentils' },
  { name: 'Black Masoor Dal', servingSize: 1, servingUnit: 'katori (150g)', calories: 135, protein: 8.8, carbs: 22.0, fats: 1.0, category: 'Dal & Lentils' },
  { name: 'Moong Dal Tadka (Dry)', servingSize: 1, servingUnit: 'katori (150g)', calories: 160, protein: 11.0, carbs: 24.0, fats: 2.5, category: 'Dal & Lentils' },
  { name: 'Kulthi (Horse Gram) Soup', servingSize: 1, servingUnit: 'bowl (200ml)', calories: 90, protein: 6.5, carbs: 14.0, fats: 1.0, category: 'Dal & Lentils' },
  { name: 'Sprouted Moth Bean Curry', servingSize: 1, servingUnit: 'katori (150g)', calories: 130, protein: 9.0, carbs: 20.0, fats: 1.5, category: 'Dal & Lentils' },
  { name: 'Rajma Jammu Style', servingSize: 1, servingUnit: 'katori (200g)', calories: 210, protein: 14.0, carbs: 36.0, fats: 1.2, category: 'Dal & Lentils' },

  { name: 'Aloo Shimla Mirch (Dry)', servingSize: 1, servingUnit: 'katori (150g)', calories: 120, protein: 2.2, carbs: 15.0, fats: 6.0, category: 'Vegetable Curry' },
  { name: 'Aloo Beans (Dry)', servingSize: 1, servingUnit: 'katori (150g)', calories: 110, protein: 2.4, carbs: 13.0, fats: 5.5, category: 'Vegetable Curry' },
  { name: 'Aloo Parwal', servingSize: 1, servingUnit: 'katori (150g)', calories: 130, protein: 2.2, carbs: 16.0, fats: 6.5, category: 'Vegetable Curry' },
  { name: 'Bhindi Do Pyaza', servingSize: 1, servingUnit: 'katori (150g)', calories: 140, protein: 2.6, carbs: 12.0, fats: 9.0, category: 'Vegetable Curry' },
  { name: 'Baingan Aloo Curry', servingSize: 1, servingUnit: 'katori (150g)', calories: 135, protein: 2.4, carbs: 15.0, fats: 7.0, category: 'Vegetable Curry' },
  { name: 'Baingan Fry (Bengali Style)', servingSize: 1, servingUnit: 'piece (50g)', calories: 95, protein: 1.0, carbs: 7.0, fats: 7.0, category: 'Vegetable Curry' },
  { name: 'Gobi Matar (Dry)', servingSize: 1, servingUnit: 'katori (150g)', calories: 115, protein: 3.5, carbs: 13.0, fats: 5.5, category: 'Vegetable Curry' },
  { name: 'Cabbage Matar', servingSize: 1, servingUnit: 'katori (150g)', calories: 95, protein: 2.8, carbs: 11.0, fats: 4.5, category: 'Vegetable Curry' },
  { name: 'Tori Masala', servingSize: 1, servingUnit: 'katori (150g)', calories: 75, protein: 1.8, carbs: 8.5, fats: 4.0, category: 'Vegetable Curry' },
  { name: 'Tinda Curry', servingSize: 1, servingUnit: 'katori (150g)', calories: 85, protein: 2.0, carbs: 9.5, fats: 4.5, category: 'Vegetable Curry' },
  { name: 'Parwal Masala', servingSize: 1, servingUnit: 'katori (150g)', calories: 120, protein: 2.5, carbs: 11.0, fats: 7.5, category: 'Vegetable Curry' },
  { name: 'Sem Aloo Curry', servingSize: 1, servingUnit: 'katori (150g)', calories: 125, protein: 2.8, carbs: 15.0, fats: 6.0, category: 'Vegetable Curry' },
  { name: 'Arbi Fry', servingSize: 1, servingUnit: 'katori (150g)', calories: 170, protein: 2.2, carbs: 24.0, fats: 7.5, category: 'Vegetable Curry' },
  { name: 'Karela Pyaza', servingSize: 1, servingUnit: 'katori (150g)', calories: 110, protein: 2.2, carbs: 10.0, fats: 7.0, category: 'Vegetable Curry' },

  { name: 'Chicken Tikka Roll', servingSize: 1, servingUnit: 'roll (200g)', calories: 320, protein: 24.0, carbs: 28.0, fats: 12.0, category: 'Non-Veg' },
  { name: 'Chicken Seekh Salad', servingSize: 1, servingUnit: 'plate (200g)', calories: 190, protein: 22.0, carbs: 6.0, fats: 8.0, category: 'Non-Veg' },
  { name: 'Chicken Keema Paratha', servingSize: 1, servingUnit: 'piece (120g)', calories: 310, protein: 16.0, carbs: 32.0, fats: 13.0, category: 'Non-Veg' },
  { name: 'Chicken Saag', servingSize: 1, servingUnit: 'katori (200g)', calories: 235, protein: 24.0, carbs: 5.5, fats: 12.5, category: 'Non-Veg' },
  { name: 'Butter Chicken (Low Fat)', servingSize: 1, servingUnit: 'katori (200g)', calories: 270, protein: 22.0, carbs: 10.0, fats: 15.0, category: 'Non-Veg' },
  { name: 'Mutton Bhuna Gosht', servingSize: 1, servingUnit: 'katori (200g)', calories: 320, protein: 26.0, carbs: 6.0, fats: 21.0, category: 'Non-Veg' },
  { name: 'Mutton Keema Kaleji', servingSize: 1, servingUnit: 'katori (200g)', calories: 340, protein: 28.0, carbs: 5.0, fats: 23.0, category: 'Non-Veg' },
  { name: 'Fish Tikka (Grilled)', servingSize: 6, servingUnit: 'pieces (150g)', calories: 180, protein: 26.0, carbs: 3.0, fats: 7.0, category: 'Non-Veg' },
  { name: 'Prawn Masala', servingSize: 1, servingUnit: 'katori (150g)', calories: 190, protein: 21.0, carbs: 7.0, fats: 8.5, category: 'Non-Veg' },
  { name: 'Crab Masala', servingSize: 1, servingUnit: 'plate (200g)', calories: 210, protein: 18.0, carbs: 8.0, fats: 11.0, category: 'Non-Veg' },
  { name: 'Egg Bhurji (Single Egg)', servingSize: 1, servingUnit: 'plate (80g)', calories: 110, protein: 7.5, carbs: 2.0, fats: 8.0, category: 'Non-Veg' },
  { name: 'Egg Masala Curry', servingSize: 1, servingUnit: 'katori (200g)', calories: 210, protein: 13.0, carbs: 6.5, fats: 14.5, category: 'Non-Veg' },
  { name: 'Boiled Egg White', servingSize: 1, servingUnit: 'piece (33g)', calories: 17, protein: 3.6, carbs: 0.2, fats: 0.1, category: 'Non-Veg' },
  { name: 'Chicken Korma (Shahi)', servingSize: 1, servingUnit: 'katori (200g)', calories: 330, protein: 21.0, carbs: 9.0, fats: 23.5, category: 'Non-Veg' },
  { name: 'Chicken Reshmi Kebab', servingSize: 4, servingUnit: 'pieces (100g)', calories: 175, protein: 22.0, carbs: 3.5, fats: 8.0, category: 'Non-Veg' },

  { name: 'Oats Dosa', servingSize: 1, servingUnit: 'piece (120g)', calories: 150, protein: 4.5, carbs: 24.0, fats: 3.8, category: 'Breakfast' },
  { name: 'Ragi Dosa', servingSize: 1, servingUnit: 'piece (120g)', calories: 145, protein: 3.8, carbs: 26.0, fats: 3.0, category: 'Breakfast' },
  { name: 'Jowar Dosa', servingSize: 1, servingUnit: 'piece (120g)', calories: 152, protein: 4.0, carbs: 25.0, fats: 3.5, category: 'Breakfast' },
  { name: 'Wheat Dosa', servingSize: 1, servingUnit: 'piece (120g)', calories: 160, protein: 4.2, carbs: 28.0, fats: 3.2, category: 'Breakfast' },
  { name: 'Oats Idli', servingSize: 2, servingUnit: 'pieces (120g)', calories: 140, protein: 5.0, carbs: 24.0, fats: 2.2, category: 'Breakfast' },
  { name: 'Ragi Idli', servingSize: 2, servingUnit: 'pieces (120g)', calories: 135, protein: 4.2, carbs: 26.0, fats: 1.5, category: 'Breakfast' },
  { name: 'Poha (Indori Style)', servingSize: 1, servingUnit: 'plate (200g)', calories: 260, protein: 5.2, carbs: 42.0, fats: 8.5, category: 'Breakfast' },
  { name: 'Vermicelli Upma', servingSize: 1, servingUnit: 'plate (200g)', calories: 215, protein: 4.8, carbs: 36.0, fats: 5.5, category: 'Breakfast' },
  { name: 'Oats Porridge (Sweet)', servingSize: 1, servingUnit: 'bowl (200g)', calories: 175, protein: 6.0, carbs: 30.0, fats: 3.2, category: 'Breakfast' },
  { name: 'Dalia (Sweet Milk)', servingSize: 1, servingUnit: 'bowl (200g)', calories: 190, protein: 6.5, carbs: 32.0, fats: 4.0, category: 'Breakfast' },
  { name: 'Besan Cheela (with Paneer)', servingSize: 2, servingUnit: 'pieces (150g)', calories: 250, protein: 13.0, carbs: 24.0, fats: 11.5, category: 'Breakfast' },

  { name: 'Onion Pakora', servingSize: 5, servingUnit: 'pieces (100g)', calories: 260, protein: 4.5, carbs: 24.0, fats: 16.5, category: 'Snack' },
  { name: 'Spinach Pakora (Palak)', servingSize: 5, servingUnit: 'pieces (100g)', calories: 240, protein: 4.8, carbs: 22.0, fats: 15.0, category: 'Snack' },
  { name: 'Paneer Pakora (Dry)', servingSize: 4, servingUnit: 'pieces (100g)', calories: 270, protein: 13.0, carbs: 14.0, fats: 18.0, category: 'Snack' },
  { name: 'Bread Pakora (Stuffed)', servingSize: 1, servingUnit: 'piece (100g)', calories: 240, protein: 5.0, carbs: 26.0, fats: 13.0, category: 'Snack' },
  { name: 'Vegetable Cutlet', servingSize: 2, servingUnit: 'pieces (100g)', calories: 190, protein: 3.5, carbs: 24.0, fats: 9.0, category: 'Snack' },
  { name: 'Corn Cutlet', servingSize: 2, servingUnit: 'pieces (100g)', calories: 200, protein: 4.0, carbs: 26.0, fats: 9.0, category: 'Snack' },
  { name: 'Samosa Chaat', servingSize: 1, servingUnit: 'plate (200g)', calories: 340, protein: 6.0, carbs: 36.0, fats: 19.5, category: 'Snack' },
  { name: 'Kachori Chaat', servingSize: 1, servingUnit: 'plate (180g)', calories: 310, protein: 6.0, carbs: 34.0, fats: 16.5, category: 'Snack' },
  { name: 'Dhokla (Sandwich)', servingSize: 4, servingUnit: 'pieces (120g)', calories: 180, protein: 6.5, carbs: 26.0, fats: 5.0, category: 'Snack' },
  { name: 'Khaman Dhokla', servingSize: 4, servingUnit: 'pieces (120g)', calories: 170, protein: 6.2, carbs: 25.0, fats: 4.5, category: 'Snack' },
  { name: 'Patra (Alu Vadi)', servingSize: 4, servingUnit: 'pieces (100g)', calories: 165, protein: 4.2, carbs: 23.0, fats: 6.2, category: 'Snack' },
  { name: 'Sabudana Vada (Air Fried)', servingSize: 2, servingUnit: 'pieces (80g)', calories: 150, protein: 2.2, carbs: 28.0, fats: 3.5, category: 'Snack' },

  { name: 'Almond Milk (Unsweetened)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 35, protein: 1.0, carbs: 1.5, fats: 2.5, category: 'Dairy' },
  { name: 'Paneer (Low Fat)', servingSize: 100, servingUnit: 'grams', calories: 175, protein: 19.5, carbs: 1.5, fats: 10.0, category: 'Dairy' },
  { name: 'Tofu (Firm)', servingSize: 100, servingUnit: 'grams', calories: 140, protein: 16.0, carbs: 2.5, fats: 7.5, category: 'Dairy' },
  { name: 'Curd (Buffalo Milk)', servingSize: 1, servingUnit: 'katori (150g)', calories: 145, protein: 5.8, carbs: 7.5, fats: 9.5, category: 'Dairy' },
  { name: 'Mango Shrikhand', servingSize: 1, servingUnit: 'katori (100g)', calories: 230, protein: 4.2, carbs: 36.0, fats: 7.5, category: 'Dairy' },
  { name: 'Mishti Doi (Sweet Curd)', servingSize: 1, servingUnit: 'cup (100g)', calories: 155, protein: 3.8, carbs: 23.0, fats: 4.8, category: 'Dairy' },
  { name: 'Rabri (Low Sugar)', servingSize: 1, servingUnit: 'katori (100g)', calories: 170, protein: 5.5, carbs: 18.0, fats: 7.5, category: 'Dairy' },
  { name: 'Masala Buttermilk (Chaas)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 42, protein: 2.1, carbs: 4.2, fats: 1.6, category: 'Dairy' },
  { name: 'Whey Protein (Isolate) scoop', servingSize: 1, servingUnit: 'scoop (30g)', calories: 115, protein: 26.0, carbs: 0.8, fats: 0.4, category: 'Dairy' },

  { name: 'Guava (Pink)', servingSize: 1, servingUnit: 'medium (100g)', calories: 65, protein: 2.4, carbs: 13.5, fats: 0.9, category: 'Fruit' },
  { name: 'Wood Apple (Bael)', servingSize: 1, servingUnit: 'medium (150g)', calories: 130, protein: 1.8, carbs: 31.0, fats: 0.3, category: 'Fruit' },
  { name: 'Star Fruit (Carambola)', servingSize: 1, servingUnit: 'medium (90g)', calories: 28, protein: 0.9, carbs: 6.0, fats: 0.3, category: 'Fruit' },
  { name: 'Mulberry (Shahtoot)', servingSize: 1, servingUnit: 'cup (140g)', calories: 60, protein: 2.0, carbs: 14.0, fats: 0.5, category: 'Fruit' },
  { name: 'Cape Gooseberry (Rasbhari)', servingSize: 10, servingUnit: 'pieces (50g)', calories: 26, protein: 0.9, carbs: 5.6, fats: 0.3, category: 'Fruit' },
  { name: 'Phalsa berries', servingSize: 50, servingUnit: 'grams', calories: 36, protein: 0.8, carbs: 8.5, fats: 0.2, category: 'Fruit' },

  { name: 'Parwal (Pointed Gourd)', servingSize: 100, servingUnit: 'grams', calories: 20, protein: 1.4, carbs: 4.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Tinda (Apple Gourd)', servingSize: 100, servingUnit: 'grams', calories: 18, protein: 1.0, carbs: 3.5, fats: 0.2, category: 'Vegetable' },
  { name: 'Colocasia Root (Arbi) boiled', servingSize: 100, servingUnit: 'grams', calories: 110, protein: 1.5, carbs: 26.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Elephant Foot Yam (Suran)', servingSize: 100, servingUnit: 'grams', calories: 120, protein: 1.8, carbs: 28.0, fats: 0.2, category: 'Vegetable' },
  { name: 'Amaranth Leaves (Chaulai)', servingSize: 100, servingUnit: 'grams', calories: 23, protein: 2.5, carbs: 4.0, fats: 0.3, category: 'Vegetable' },
  { name: 'Bathua Leaves raw', servingSize: 100, servingUnit: 'grams', calories: 30, protein: 4.0, carbs: 4.5, fats: 0.5, category: 'Vegetable' },
  { name: 'Fenugreek Leaves (Methi)', servingSize: 100, servingUnit: 'grams', calories: 49, protein: 4.4, carbs: 6.0, fats: 0.9, category: 'Vegetable' },

  { name: 'Masala Chai (Stevia/No Sugar)', servingSize: 1, servingUnit: 'cup (150ml)', calories: 30, protein: 2.0, carbs: 3.0, fats: 1.0, category: 'Beverage' },
  { name: 'Filter Coffee (Stevia/No Sugar)', servingSize: 1, servingUnit: 'cup (150ml)', calories: 35, protein: 2.0, carbs: 3.0, fats: 1.5, category: 'Beverage' },
  { name: 'Kokum Sharbat (Low Sugar)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 70, protein: 0.2, carbs: 17.0, fats: 0.1, category: 'Beverage' },
  { name: 'Aam Panna (Low Sugar)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 75, protein: 0.4, carbs: 18.0, fats: 0.1, category: 'Beverage' },
  { name: 'Jaljeera (Low Sugar)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 25, protein: 0.4, carbs: 5.5, fats: 0.1, category: 'Beverage' },
  { name: 'Mint Lemonade (No Sugar)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 12, protein: 0.1, carbs: 2.5, fats: 0.0, category: 'Beverage' },
  { name: 'Barley Water', servingSize: 1, servingUnit: 'glass (250ml)', calories: 80, protein: 1.2, carbs: 18.0, fats: 0.2, category: 'Beverage' },
  { name: 'Sattu Sherbet (Salted)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 120, protein: 6.0, carbs: 20.0, fats: 2.0, category: 'Beverage' },
  { name: 'Thandai (Low Fat)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 180, protein: 5.5, carbs: 24.0, fats: 7.0, category: 'Beverage' },
  { name: 'Rose Sharbat (Low Sugar)', servingSize: 1, servingUnit: 'glass (250ml)', calories: 95, protein: 0.0, carbs: 24.0, fats: 0.0, category: 'Beverage' },

  { name: 'Motichoor Ladoo piece', servingSize: 1, servingUnit: 'piece (40g)', calories: 170, protein: 2.0, carbs: 24.0, fats: 8.0, category: 'Sweets' },
  { name: 'Pista Barfi piece', servingSize: 1, servingUnit: 'piece (30g)', calories: 135, protein: 3.0, carbs: 15.0, fats: 7.0, category: 'Sweets' },
  { name: 'Besan Ladoo piece', servingSize: 1, servingUnit: 'piece (40g)', calories: 185, protein: 3.5, carbs: 22.0, fats: 9.0, category: 'Sweets' },
  { name: 'Sohan Papdi block', servingSize: 1, servingUnit: 'piece (35g)', calories: 160, protein: 2.0, carbs: 20.0, fats: 8.0, category: 'Sweets' },
  { name: 'Peda (Mathura peda)', servingSize: 1, servingUnit: 'piece (25g)', calories: 105, protein: 2.5, carbs: 13.0, fats: 4.5, category: 'Sweets' },
  { name: 'Ghevar round', servingSize: 1, servingUnit: 'piece (80g)', calories: 320, protein: 4.0, carbs: 45.0, fats: 14.0, category: 'Sweets' },
  { name: 'Chhena Poda slice', servingSize: 1, servingUnit: 'slice (80g)', calories: 160, protein: 6.0, carbs: 24.0, fats: 5.0, category: 'Sweets' },
  { name: 'Adhirasam sweet', servingSize: 1, servingUnit: 'piece (50g)', calories: 210, protein: 3.0, carbs: 32.0, fats: 8.0, category: 'Sweets' },
  { name: 'Unniyappam round', servingSize: 3, servingUnit: 'pieces (75g)', calories: 230, protein: 3.5, carbs: 35.0, fats: 8.5, category: 'Sweets' },
  { name: 'Karanji (Gujiya pastry)', servingSize: 1, servingUnit: 'piece (50g)', calories: 190, protein: 3.0, carbs: 26.0, fats: 8.5, category: 'Sweets' },

  { name: 'Schezwan Fried Rice plate', servingSize: 1, servingUnit: 'plate (250g)', calories: 360, protein: 6.5, carbs: 52.0, fats: 14.0, category: 'Street Food' },
  { name: 'Egg Fried Rice plate', servingSize: 1, servingUnit: 'plate (250g)', calories: 360, protein: 12.0, carbs: 48.0, fats: 14.0, category: 'Street Food' },
  { name: 'Pav Bhaji (Low Butter)', servingSize: 1, servingUnit: 'plate (300g)', calories: 320, protein: 9.5, carbs: 46.0, fats: 11.0, category: 'Street Food' },
  { name: 'Veg Chowmein', servingSize: 1, servingUnit: 'plate (250g)', calories: 330, protein: 5.8, carbs: 50.0, fats: 12.0, category: 'Street Food' },
  { name: 'Paneer Chowmein', servingSize: 1, servingUnit: 'plate (250g)', calories: 390, protein: 13.5, carbs: 48.0, fats: 16.0, category: 'Street Food' },
  { name: 'Chicken Chowmein', servingSize: 1, servingUnit: 'plate (250g)', calories: 410, protein: 18.0, carbs: 46.0, fats: 16.5, category: 'Street Food' },
  { name: 'Gobi Manchurian (Dry)', servingSize: 1, servingUnit: 'plate (200g)', calories: 240, protein: 4.5, carbs: 26.0, fats: 13.5, category: 'Street Food' },
  { name: 'Baby Corn Manchurian', servingSize: 1, servingUnit: 'plate (200g)', calories: 260, protein: 4.8, carbs: 28.0, fats: 14.0, category: 'Street Food' },
  { name: 'Chilli Paneer (Dry)', servingSize: 1, servingUnit: 'plate (200g)', calories: 300, protein: 13.5, carbs: 14.0, fats: 21.0, category: 'Street Food' },
  { name: 'Veg Spring Roll', servingSize: 2, servingUnit: 'pieces (100g)', calories: 210, protein: 3.8, carbs: 25.0, fats: 10.5, category: 'Street Food' },
  { name: 'Chicken Spring Roll', servingSize: 2, servingUnit: 'pieces (100g)', calories: 240, protein: 11.5, carbs: 23.0, fats: 11.5, category: 'Street Food' },
  { name: 'Veg Momos (Steamed)', servingSize: 6, servingUnit: 'pieces (150g)', calories: 210, protein: 5.8, carbs: 33.0, fats: 5.8, category: 'Street Food' },
  { name: 'Chicken Momos (Steamed)', servingSize: 6, servingUnit: 'pieces (150g)', calories: 250, protein: 13.5, carbs: 29.0, fats: 7.8, category: 'Street Food' },
  { name: 'Veg Momos (Fried)', servingSize: 6, servingUnit: 'pieces (150g)', calories: 320, protein: 5.8, carbs: 33.0, fats: 18.0, category: 'Street Food' },
  { name: 'Chicken Momos (Fried)', servingSize: 6, servingUnit: 'pieces (150g)', calories: 360, protein: 13.5, carbs: 29.0, fats: 20.0, category: 'Street Food' },
  { name: 'Sev Khaman', servingSize: 1, servingUnit: 'plate (150g)', calories: 210, protein: 7.0, carbs: 28.0, fats: 8.0, category: 'Street Food' },
  { name: 'Aloo Patty', servingSize: 1, servingUnit: 'piece (80g)', calories: 220, protein: 3.5, carbs: 24.0, fats: 12.0, category: 'Street Food' },
  { name: 'Paneer Patty', servingSize: 1, servingUnit: 'piece (90g)', calories: 260, protein: 8.5, carbs: 22.0, fats: 15.0, category: 'Street Food' },
  { name: 'Bread Butter Jam', servingSize: 2, servingUnit: 'slices (70g)', calories: 220, protein: 4.2, carbs: 38.0, fats: 6.0, category: 'Street Food' },
  { name: 'Cheese Chutney Sandwich', servingSize: 1, servingUnit: 'sandwich (120g)', calories: 260, protein: 9.0, carbs: 28.0, fats: 12.0, category: 'Street Food' },
  { name: 'Club Sandwich Veg', servingSize: 1, servingUnit: 'sandwich (200g)', calories: 340, protein: 10.5, carbs: 42.0, fats: 14.5, category: 'Street Food' },
  { name: 'Chilli Cheese Toast', servingSize: 2, servingUnit: 'slices (100g)', calories: 280, protein: 11.0, carbs: 26.0, fats: 14.5, category: 'Street Food' },
  { name: 'Masala French Fries', servingSize: 1, servingUnit: 'medium (100g)', calories: 320, protein: 3.5, carbs: 42.0, fats: 15.5, category: 'Street Food' },
  { name: 'Misal Pav plate', servingSize: 1, servingUnit: 'plate (300g)', calories: 380, protein: 13.0, carbs: 48.0, fats: 15.0, category: 'Street Food' },
  { name: 'Usal Pav plate', servingSize: 1, servingUnit: 'plate (300g)', calories: 350, protein: 12.5, carbs: 46.0, fats: 12.5, category: 'Street Food' }
];

async function main() {
  console.log(`🌱 Seeding ${indianFoods.length} Indian food items...`);

  let created = 0;
  let skipped = 0;

  for (const food of indianFoods) {
    const id = `default-food-${food.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;

    try {
      await prisma.food.upsert({
        where: { id },
        update: {
          calories: food.calories,
          protein: food.protein,
          carbs: food.carbs,
          fats: food.fats,
          servingSize: food.servingSize,
          servingUnit: food.servingUnit,
          category: food.category,
        },
        create: {
          id,
          name: food.name,
          servingSize: food.servingSize,
          servingUnit: food.servingUnit,
          calories: food.calories,
          protein: food.protein,
          carbs: food.carbs,
          fats: food.fats,
          category: food.category,
          isDefault: true,
        },
      });
      created++;
    } catch (err) {
      skipped++;
      console.warn(`⚠ Skipped: ${food.name}`);
    }
  }

  console.log(`✅ Seeding complete! ${created} foods created/updated, ${skipped} skipped.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
